(function () {
  const BANK_JT_SEM2 = {
    id: "jt-sem2",
    name: "教圖下學期考試版",
    questions: [
      { id: "jtsem2-001", source: "兵車行", type: "內容理解", question: "《兵車行》開首「車轔轔，馬蕭蕭」主要營造怎樣的氣氛？", options: ["緊張悲涼", "輕快歡樂", "安閒寧靜", "悠然閒適"], answer: 0, explanation: "車馬喧鬧聲配合送別場景，營造出戰亂徵發的緊張與悲苦。", diff: 1 },
      { id: "jtsem2-002", source: "兵車行", type: "內容理解", question: "《兵車行》中，送別出征者的是哪些人？", options: ["爺娘妻子", "文人雅士", "宮使宦官", "商旅客人"], answer: 0, explanation: "詩中明言「爺娘妻子走相送」，寫出家人送別的場面。", diff: 1 },
      { id: "jtsem2-003", source: "兵車行", type: "內容理解", question: "「牽衣頓足攔道哭」最能表現送行者甚麼感情？", options: ["極度悲痛", "滿懷期待", "興奮激昂", "冷淡平靜"], answer: 0, explanation: "透過動作描寫，具體表現送別親人時的強烈悲痛。", diff: 1 },
      { id: "jtsem2-004", source: "兵車行", type: "語句理解", question: "「行人但云點行頻」中的「點行頻」是指甚麼？", options: ["徵兵頻繁", "點名表演", "巡察頻密", "行軍整齊"], answer: 0, explanation: "「點行頻」指朝廷頻頻點兵徵發，百姓不堪其苦。", diff: 1 },
      { id: "jtsem2-005", source: "兵車行", type: "內容理解", question: "「或從十五北防河，便至四十西營田」主要說明甚麼？", options: ["兵役時間極長", "人人自願從軍", "邊境農作發達", "將士地位崇高"], answer: 0, explanation: "從十五歲到四十歲仍在服役，反映兵役漫長沉重。", diff: 1 },
      { id: "jtsem2-006", source: "兵車行", type: "語句理解", question: "「去時里正與裹頭，歸來頭白還戍邊」的作用是甚麼？", options: ["突出戰役時間拖長人生", "說明地方官關懷百姓", "表現士兵回鄉光榮", "顯示軍中生活富裕"], answer: 0, explanation: "年少出征，白頭仍戍邊，極寫戰事與兵役耗盡一生。", diff: 2 },
      { id: "jtsem2-007", source: "兵車行", type: "修辭手法", question: "「邊庭流血成海水」運用了甚麼修辭？", options: ["誇飾", "借代", "互文", "頂真"], answer: 0, explanation: "以誇張方式突顯戰爭死傷慘重。", diff: 2 },
      { id: "jtsem2-008", source: "兵車行", type: "內容理解", question: "「武皇開邊意未已」主要批評甚麼？", options: ["統治者窮兵黷武", "士兵不善作戰", "邊地氣候惡劣", "百姓不願守土"], answer: 0, explanation: "詩人批評統治者不斷開邊用兵，導致民不聊生。", diff: 2 },
      { id: "jtsem2-009", source: "兵車行", type: "內容理解", question: "「千村萬落生荊杞」描寫了怎樣的景象？", options: ["農村荒蕪", "農作豐收", "村落繁華", "田野整齊"], answer: 0, explanation: "荊杞叢生表示村落失修荒廢，農地無人治理。", diff: 2 },
      { id: "jtsem2-010", source: "兵車行", type: "內容理解", question: "「縱有健婦把鋤犁，禾生隴畝無東西」反映甚麼問題？", options: ["農業生產受嚴重破壞", "婦女地位顯著提高", "農村人手充足", "百姓生活安定"], answer: 0, explanation: "即使有婦女耕作，也難彌補壯丁被徵去後的農耕荒廢。", diff: 2 },
      { id: "jtsem2-011", source: "兵車行", type: "語句理解", question: "「被驅不異犬與雞」一句最能表達甚麼？", options: ["人民被視如牲畜般驅使", "軍中管理井然有序", "士兵善戰勇猛", "百姓生活與禽畜接近"], answer: 0, explanation: "以犬雞作喻，極寫百姓被迫從軍、毫無尊嚴。", diff: 3 },
      { id: "jtsem2-012", source: "兵車行", type: "內容理解", question: "「長者雖有問，役夫敢伸恨？」反映役夫怎樣的處境？", options: ["連怨恨也不敢明言", "能自由發表不滿", "樂於回答路人問題", "願意繼續從軍"], answer: 0, explanation: "「敢伸恨」說明即使心中怨恨，也不敢公開訴說。", diff: 3 },
      { id: "jtsem2-013", source: "兵車行", type: "內容理解", question: "「縣官急索租，租稅從何出？」反映百姓承受哪兩重痛苦？", options: ["戰亂與賦稅雙重壓迫", "災荒與瘟疫雙重夾擊", "遠行與離別雙重打擊", "寒冷與飢餓雙重折磨"], answer: 0, explanation: "戰亂使農村荒蕪，官府卻仍急索租稅，百姓苦不堪言。", diff: 3 },
      { id: "jtsem2-014", source: "兵車行", type: "思想感情", question: "「信知生男惡，反是生女好」表達了怎樣的社會悲哀？", options: ["戰爭使人不願生男", "社會重男輕女", "女子不能出嫁", "男子不能耕作"], answer: 0, explanation: "在戰亂背景下，生男意味着可能被徵去送死。", diff: 3 },
      { id: "jtsem2-015", source: "兵車行", type: "結尾作用", question: "「新鬼煩冤舊鬼哭，天陰雨濕聲啾啾」有甚麼作用？", options: ["把戰禍慘況推向極致", "轉入神怪故事", "描寫自然風光", "表現軍旅壯盛"], answer: 0, explanation: "以鬼哭烘托戰爭無數冤魂，收束全詩於極度悲涼的氣氛。", diff: 4 },
      { id: "jtsem2-016", source: "兵車行", type: "主旨", question: "《兵車行》的主旨最接近下列哪一項？", options: ["控訴戰爭與苛政對人民的摧殘", "歌頌將士為國犧牲", "描寫送別場面感人", "讚美邊塞風光壯麗"], answer: 0, explanation: "杜甫藉送別與戰後景象，深刻揭露窮兵黷武害民。", diff: 4 },
      { id: "jtsem2-017", source: "兵車行", type: "寫作手法", question: "《兵車行》從送別場面寫到荒村、稅役與鬼哭，最能說明其結構特色是甚麼？", options: ["由局部推向整體災難", "先議論後抒情", "首尾不相照應", "純粹景物鋪陳"], answer: 0, explanation: "作者由眼前的送別場面層層推展至整個時代的民生苦況。", diff: 4 },
      { id: "jtsem2-018", source: "兵車行", type: "細節理解", question: "「塵埃不見咸陽橋」的作用最主要是甚麼？", options: ["寫出送行人數眾多、場面混亂", "描寫風景優美", "交代天氣惡劣", "預示戰事將勝"], answer: 0, explanation: "塵土飛揚遮蔽橋梁，側面寫出送行場面之擁擠與悲亂。", diff: 3 },
      { id: "jtsem2-019", source: "兵車行", type: "人物處境", question: "詩中的「行人」是指哪一類人？", options: ["被徵發出征的百姓", "路過的旅客", "城中的商人", "宮中的使者"], answer: 0, explanation: "結合上下文可知，「行人」指被徵召的士兵。", diff: 2 },
      { id: "jtsem2-020", source: "兵車行", type: "賞析", question: "《兵車行》被視為反戰詩，最主要原因是甚麼？", options: ["它從人民角度寫戰亂之害", "它讚揚軍功建立", "它描寫將軍威武", "它記錄出征程序"], answer: 0, explanation: "杜甫並非從勝負角度寫戰爭，而是聚焦人民遭遇。", diff: 4 },

      { id: "jtsem2-021", source: "靜虛村記", type: "內容理解", question: "《靜虛村記》開首指出，在大城市附近最難找到的是甚麼地方？", options: ["清靜拙樸之地", "高樓大廈之地", "繁華熱鬧之地", "車站工廠之地"], answer: 0, explanation: "作者說找熱鬧繁華容易，尋清靜拙樸反而困難。", diff: 1 },
      { id: "jtsem2-022", source: "靜虛村記", type: "內容理解", question: "作者為何會住進靜虛村？", options: ["租賃農家民房棲身", "回鄉務農", "被朝廷貶謫", "隨軍駐守邊地"], answer: 0, explanation: "文中直接交代作者租下農家民房棲身。", diff: 1 },
      { id: "jtsem2-023", source: "靜虛村記", type: "內容理解", question: "作者形容靜虛村處於現代建築之間，像甚麼一樣？", options: ["颱風中心反倒平靜", "汪洋中的孤舟", "沙漠中的綠洲", "高山上的古寺"], answer: 0, explanation: "作者說「奇怪颱風中心反倒平靜一樣」，形容其難得的安靜。", diff: 2 },
      { id: "jtsem2-024", source: "靜虛村記", type: "內容理解", question: "友人來到作者家中，對村子的評價最接近哪一項？", options: ["質樸渾拙而典雅", "華麗奢侈而炫目", "荒涼破敗而無趣", "陰森可怖而神秘"], answer: 0, explanation: "友人把這裡比作古老民歌、枯井鮮水、出土青瓷，皆指向質樸典雅。", diff: 2 },
      { id: "jtsem2-025", source: "靜虛村記", type: "景物理解", question: "作者初見村子時，先看到的是甚麼？", options: ["濃重如綠雲般的樹", "成排整齊的樓房", "寬闊平直的馬路", "熱鬧擁擠的市場"], answer: 0, explanation: "作者先寫樹枝葉交錯如濃重綠雲，之後才走近見村。", diff: 2 },
      { id: "jtsem2-026", source: "靜虛村記", type: "景物理解", question: "村子外的土牆有甚麼特點？", options: ["生滿厚厚綠苔", "粉刷得雪白平滑", "鑲滿彩色瓷磚", "完全殘破坍塌"], answer: 0, explanation: "作者寫土牆完好無缺，並生了厚厚綠苔。", diff: 1 },
      { id: "jtsem2-027", source: "靜虛村記", type: "內容理解", question: "村中巷道的形狀是甚麼？", options: ["U 形", "十字形", "圓環形", "一直線形"], answer: 0, explanation: "作者明言兩條巷道其實連在一起，是個 U 形。", diff: 1 },
      { id: "jtsem2-028", source: "靜虛村記", type: "內容理解", question: "村中多是茅屋，原因是甚麼？", options: ["冬暖夏涼又抗震", "村人太窮建不起瓦屋", "政府禁止蓋高樓", "方便拆卸搬遷"], answer: 0, explanation: "作者特別指出這不是寒酸，而是村人的講究。", diff: 2 },
      { id: "jtsem2-029", source: "靜虛村記", type: "人物理解", question: "《靜虛村記》中，作者筆下的村人有何特點？", options: ["厚誠樸實", "冷漠精明", "狡猾多疑", "虛偽勢利"], answer: 0, explanation: "文中說村人十分厚誠，幾乎近於傻味。", diff: 1 },
      { id: "jtsem2-030", source: "靜虛村記", type: "人物理解", question: "村人對過路行人的態度如何？", options: ["有問必答，還會帶路指點", "故意敷衍，不理不睬", "只回答認識的人", "先收錢再指路"], answer: 0, explanation: "作者寫村人會比比劃劃說明，甚至領到村口。", diff: 2 },
      { id: "jtsem2-031", source: "靜虛村記", type: "生活描寫", question: "村人吃飯時有甚麼習慣？", options: ["集在巷中就地而蹲", "分坐雅室細嚼慢嚥", "人人端坐餐桌", "邊走邊吃不作停留"], answer: 0, explanation: "作者特意指出村人習慣在巷中蹲着吃飯。", diff: 2 },
      { id: "jtsem2-032", source: "靜虛村記", type: "內容理解", question: "作者家裡和村裡都很少花，主要原因是甚麼？", options: ["花常枯死萎縮", "村民討厭花草", "土地不能種花", "氣候太冷嚴寒"], answer: 0, explanation: "文中說曾經栽過多次，總是枯死或萎縮。", diff: 2 },
      { id: "jtsem2-033", source: "靜虛村記", type: "人物描寫", question: "作者寫村中女兒們「個個有桃花水色」，主要是為了表現甚麼？", options: ["她們自然健康而美好", "她們愛慕虛榮", "她們十分嬌弱", "她們不愛勞作"], answer: 0, explanation: "這裡是帶欣賞意味的描寫，表現村中女子自然清秀。", diff: 3 },
      { id: "jtsem2-034", source: "靜虛村記", type: "內容理解", question: "村中最多的樹是甚麼？", options: ["槐樹", "楊樹", "竹子", "榕樹"], answer: 0, explanation: "作者直接說「啥樹都有，最多的，要數槐樹」。", diff: 1 },
      { id: "jtsem2-035", source: "靜虛村記", type: "生活描寫", question: "槐花開時，村人通常會怎樣做？", options: ["做槐花蒸飯", "拿來賣到城裡", "供奉祖先", "染布製衣"], answer: 0, explanation: "文中寫槐花開放時，家家都做槐花蒸飯。", diff: 1 },
      { id: "jtsem2-036", source: "靜虛村記", type: "內容理解", question: "作者家中出奇地有幾個燕子窩？", options: ["三個", "一個", "兩個", "四個"], answer: 0, explanation: "作者明說自己茅屋樑上出奇地有三個燕子窩。", diff: 1 },
      { id: "jtsem2-037", source: "靜虛村記", type: "景物理解", question: "作者認為村中最妙的是甚麼？", options: ["巷中的一眼井", "門前的大槐樹", "屋後的菜園", "村外的車站"], answer: 0, explanation: "文中有「最妙的是巷中一眼井」一句。", diff: 1 },
      { id: "jtsem2-038", source: "靜虛村記", type: "內容理解", question: "作者認為井水有甚麼特點？", options: ["甘甜清涼，生喝比熟喝味長", "混濁難飲", "只適合洗衣", "帶有苦澀味"], answer: 0, explanation: "文中以味覺與感受突出井水之佳。", diff: 2 },
      { id: "jtsem2-039", source: "靜虛村記", type: "內容理解", question: "作者寧可天天擔井水，也不願怎樣？", options: ["去擰自來水", "到河邊洗衣", "進城買水", "請人代勞"], answer: 0, explanation: "作者覺得井水更好，因此不願使用自來水。", diff: 2 },
      { id: "jtsem2-040", source: "靜虛村記", type: "思想感情", question: "吃了半年井水後，作者自覺有甚麼改變？", options: ["心脾清爽，作文更有精神靈性", "身體變差，精神疲倦", "覺得村居無趣", "更思念城市生活"], answer: 0, explanation: "作者說自己看書作文更有精神與靈性了。", diff: 2 },

      { id: "jtsem2-041", source: "靜虛村記", type: "內容理解", question: "作者後來對城裡樓房的態度是甚麼？", options: ["覺得大可不必羨慕", "仍然十分嚮往", "打算搬回城裡", "覺得更有安全感"], answer: 0, explanation: "經過村居生活後，作者重新思考樓房生活的價值。", diff: 2 },
      { id: "jtsem2-042", source: "靜虛村記", type: "比喻理解", question: "作者形容住高樓「如鳥懸案」，想表達甚麼？", options: ["高樓生活脫離土地與自然", "高樓生活自由開闊", "高樓生活安全穩固", "高樓生活明亮舒適"], answer: 0, explanation: "「上不著天，下不踏地」正是指與自然土地疏離。", diff: 3 },
      { id: "jtsem2-043", source: "靜虛村記", type: "內容理解", question: "作者在土院裡種些甚麼？", options: ["白菜青蔥", "桃李梅菊", "藥材花卉", "竹子蘭花"], answer: 0, explanation: "作者說自己種些白菜青蔥，體會農家生活。", diff: 1 },
      { id: "jtsem2-044", source: "靜虛村記", type: "內容理解", question: "夜裡鑽入作者家中的蝴蝶有何特徵？", options: ["大而五彩斑斕", "很小而灰暗", "只有黑白兩色", "總是成群結隊"], answer: 0, explanation: "作者寫蝴蝶大如小女手掌，且五彩斑斕。", diff: 2 },
      { id: "jtsem2-045", source: "靜虛村記", type: "人物感情", question: "作者一家捉到蝴蝶後怎樣處理？", options: ["捉出去放了", "收藏起來", "做成標本", "拿去賣錢"], answer: 0, explanation: "作者寫一家人喜愛不已，但不願傷生。", diff: 1 },
      { id: "jtsem2-046", source: "靜虛村記", type: "內容理解", question: "作者門前的槐樹有甚麼特點？", options: ["唯獨向橫里發展，樹冠半圓", "筆直高聳，枝葉稀少", "低矮彎曲，滿樹藤蔓", "四季枯黃，毫無生氣"], answer: 0, explanation: "作者觀察細緻，描寫門前槐樹橫向生長、樹冠如裁。", diff: 2 },
      { id: "jtsem2-047", source: "靜虛村記", type: "內容理解", question: "每天聚在槐樹下的人們主要做甚麼？", options: ["談天說笑", "讀書吟詩", "打架爭執", "交易買賣"], answer: 0, explanation: "村人在槐下談政策、談家常，談笑風生。", diff: 2 },
      { id: "jtsem2-048", source: "靜虛村記", type: "內容理解", question: "後來來求作者的人越來越多，最初多為甚麼事？", options: ["代寫書信", "請他耕田", "借錢買地", "替人治病"], answer: 0, explanation: "作者先替村人代寫書信，因此知道各家的情況。", diff: 2 },
      { id: "jtsem2-049", source: "靜虛村記", type: "內容理解", question: "後來村人更常帶孩子來找作者，是希望他做甚麼？", options: ["輔導作文與功課", "教孩子耕作", "替孩子治病", "帶孩子進城"], answer: 0, explanation: "作者後來收學生，在院裡輔導作文。", diff: 2 },
      { id: "jtsem2-050", source: "靜虛村記", type: "內容理解", question: "兩年之間，村裡考中多少大學生？", options: ["五名", "三名", "十名", "十五名"], answer: 0, explanation: "作者說村裡考中了大學生五名，中專生十名。", diff: 2 },

      { id: "jtsem2-051", source: "靜虛村記", type: "情感理解", question: "天旱時，作者與村人的反應如何？", options: ["同樣焦慮", "毫不在意", "幸災樂禍", "立刻離村"], answer: 0, explanation: "作者已深深融入村人生活，所以會與村人一同焦慮。", diff: 3 },
      { id: "jtsem2-052", source: "靜虛村記", type: "情感理解", question: "下雨時，作者在雨地裡奔跑，最能說明甚麼？", options: ["他已真切融入鄉村生活", "他性格十分怪異", "他討厭在屋中避雨", "他急著去田裡工作"], answer: 0, explanation: "作者與村人一同為下雨歡喜，顯示與村子感情深厚。", diff: 3 },
      { id: "jtsem2-053", source: "靜虛村記", type: "內容理解", question: "作者的小女兒在村中有何地位？", options: ["成了村人一大玩物", "常被人疏遠", "幾乎無人認識", "總在家中獨坐"], answer: 0, explanation: "作者用帶愛意的語氣寫女兒深受村人喜愛。", diff: 2 },
      { id: "jtsem2-054", source: "靜虛村記", type: "內容理解", question: "作者的妻子在村中人緣如何？", options: ["極好，人人稱讚", "平平無奇", "常與人爭執", "與村人疏離"], answer: 0, explanation: "文中說她一應大小應酬，人人稱讚。", diff: 2 },
      { id: "jtsem2-055", source: "靜虛村記", type: "人物理解", question: "作者說自己是「世上最呆的人」，其實想表達甚麼？", options: ["自己喜歡靜思與寫作", "自己真的愚笨無知", "自己不會與人相處", "自己做事總出錯"], answer: 0, explanation: "這是自我調侃，實際上是說自己喜靜、好思、善寫。", diff: 3 },
      { id: "jtsem2-056", source: "靜虛村記", type: "內容理解", question: "村人有了新鮮事後，通常會怎樣對作者？", options: ["跑來對他敘說", "故意隱瞞不說", "到城裡找別人", "寫信通知他"], answer: 0, explanation: "村人知道作者喜歡寫作，所以會把新鮮事告訴他。", diff: 2 },
      { id: "jtsem2-057", source: "靜虛村記", type: "結構理解", question: "作者在篇末記下此文，並說一份為序、一份為跋，主要有何作用？", options: ["加強文章與村子的真切關係", "單純炫耀文學技巧", "說明文章原本不是寫村子", "表示準備離村忘記一切"], answer: 0, explanation: "這樣的收束方式使文章更像對靜虛村的鄭重記錄與珍藏。", diff: 4 },
      { id: "jtsem2-058", source: "靜虛村記", type: "主旨", question: "《靜虛村記》的主旨最接近哪一項？", options: ["歌詠鄉村拙樸自然與濃厚人情", "批評村人保守落後", "描寫城市繁榮便利", "抒發戰亂離散之痛"], answer: 0, explanation: "全文以喜愛、欣賞的筆調寫靜虛村景、人、事。", diff: 3 },
      { id: "jtsem2-059", source: "靜虛村記", type: "寫作手法", question: "《靜虛村記》大量書寫樹、井、水、雞、燕、村人、孩子等，最主要的效果是甚麼？", options: ["從多方面塑造鮮活的村居世界", "使文章失去中心", "單純增加篇幅", "轉移讀者注意"], answer: 0, explanation: "作者從自然、生活、人情多面向展現靜虛村的完整風貌。", diff: 4 },
      { id: "jtsem2-060", source: "靜虛村記", type: "深層理解", question: "《靜虛村記》中，作者真正珍視的不是村子的貧或舊，而是甚麼？", options: ["拙樸、自然與人情厚度", "交通位置便利", "土地價格便宜", "房屋建築古老"], answer: 0, explanation: "作者所欣賞的是與城市相對的自然生命感與人情味。", diff: 4 },

      { id: "jtsem2-061", source: "論四端", type: "內容理解", question: "《論四端》中，孟子提出人皆有甚麼？", options: ["不忍人之心", "逐利之心", "競爭之心", "恐懼之心"], answer: 0, explanation: "孟子以「人皆有不忍人之心」立論。", diff: 1 },
      { id: "jtsem2-062", source: "論四端", type: "內容理解", question: "孟子用「乍見孺子將入於井」的例子，是為了說明甚麼？", options: ["人本有惻隱之心", "人人都怕井", "父母之愛最重要", "仁政靠法律建立"], answer: 0, explanation: "此例證明人在自然狀態下會生起惻隱之心。", diff: 1 },
      { id: "jtsem2-063", source: "論四端", type: "內容理解", question: "孟子認為見孺子將入井時，人之所以生出惻隱，不是因為甚麼？", options: ["想和孺子父母交好", "孩子可能受傷", "人有同情本性", "情緒自然觸動"], answer: 0, explanation: "孟子特別指出這種心不是出於「內交於孺子之父母」。", diff: 2 },
      { id: "jtsem2-064", source: "論四端", type: "內容理解", question: "《論四端》中，「惻隱之心」是甚麼的開端？", options: ["仁", "義", "禮", "智"], answer: 0, explanation: "孟子說「惻隱之心，仁之端也」。", diff: 1 },
      { id: "jtsem2-065", source: "論四端", type: "內容理解", question: "《論四端》中，「羞惡之心」是甚麼的開端？", options: ["義", "仁", "禮", "信"], answer: 0, explanation: "孟子說「羞惡之心，義之端也」。", diff: 1 },
      { id: "jtsem2-066", source: "論四端", type: "內容理解", question: "《論四端》中，「辭讓之心」是甚麼的開端？", options: ["禮", "仁", "智", "勇"], answer: 0, explanation: "孟子說「辭讓之心，禮之端也」。", diff: 1 },
      { id: "jtsem2-067", source: "論四端", type: "內容理解", question: "《論四端》中，「是非之心」是甚麼的開端？", options: ["智", "禮", "仁", "義"], answer: 0, explanation: "孟子說「是非之心，智之端也」。", diff: 1 },
      { id: "jtsem2-068", source: "論四端", type: "內容理解", question: "孟子提出的「四端」不包括哪一項？", options: ["勇敢之心", "惻隱之心", "羞惡之心", "辭讓之心"], answer: 0, explanation: "四端是惻隱、羞惡、辭讓、是非，不包括勇敢。", diff: 2 },
      { id: "jtsem2-069", source: "論四端", type: "比喻理解", question: "「人之有是四端也，猶其有四體也」這句比喻想說明甚麼？", options: ["四端是與生俱來的", "四端比身體更重要", "四端可以隨意更換", "四端只屬於聖人"], answer: 0, explanation: "正如四肢是人天生具有，四端亦是人本具之善性。", diff: 2 },
      { id: "jtsem2-070", source: "論四端", type: "語句理解", question: "「有是四端而自謂不能者，自賊者也」中的「自賊」是甚麼意思？", options: ["自我傷害、自我埋沒善性", "自我保護", "自我稱讚", "自我犧牲"], answer: 0, explanation: "孟子指人若明明有善端卻不肯承認與發展，等於自我戕賊。", diff: 3 },
      { id: "jtsem2-071", source: "論四端", type: "內容理解", question: "孟子認為若能擴充四端，最終可以怎樣？", options: ["足以保四海", "必定成為君王", "不用再學習", "超越一切法律"], answer: 0, explanation: "文末說「苟能充之，足以保四海」。", diff: 2 },
      { id: "jtsem2-072", source: "論四端", type: "內容理解", question: "若不擴充四端，孟子認為最直接的結果是甚麼？", options: ["不足以事父母", "會失去財富", "會被人放逐", "無法從軍"], answer: 0, explanation: "孟子指出若不充之，甚至不足以侍奉父母。", diff: 2 },
      { id: "jtsem2-073", source: "論四端", type: "論證方法", question: "《論四端》最主要運用了甚麼論證方式？", options: ["舉例與推論結合", "景物描寫", "故事鋪陳", "神話寓言"], answer: 0, explanation: "孟子先舉孺子將入井之例，再推演四端與人性。", diff: 3 },
      { id: "jtsem2-074", source: "論四端", type: "主旨", question: "《論四端》的中心思想最接近下列哪一項？", options: ["人性本具善端，應加以培養擴充", "禮法比人心更重要", "人皆自私，必須強制教化", "天下為家是最理想社會"], answer: 0, explanation: "本文重在闡釋孟子的性善論與修養觀。", diff: 3 },
      { id: "jtsem2-075", source: "論四端", type: "深層理解", question: "孟子把四端與治國連結起來，說明他認為甚麼？", options: ["個人德性可推及政治實踐", "政治與道德毫無關係", "只需制度不需人心", "仁義只適用家庭"], answer: 0, explanation: "孟子強調由內在善端出發，可以形成仁政並治理天下。", diff: 4 },
      { id: "jtsem2-076", source: "論四端", type: "細節理解", question: "孟子連用多個「非……也」，主要有何作用？", options: ["層層排除功利動機", "增加文章節奏感而已", "表現說話猶豫", "描寫情緒激動"], answer: 0, explanation: "這樣寫是為了證明惻隱之心不是出於外在目的。", diff: 4 },
      { id: "jtsem2-077", source: "論四端", type: "價值理解", question: "依孟子之見，是否每個人都可能成就君子人格？", options: ["是，只要能擴充四端", "否，只有聖人生來如此", "否，必須出身貴族", "是，但只靠法律即可"], answer: 0, explanation: "因四端人人皆有，所以每個人都具有成德的可能。", diff: 4 },
      { id: "jtsem2-078", source: "論四端", type: "人物思想", question: "《論四端》最能體現孟子哪一方面的思想？", options: ["性善論", "無為而治", "兼愛非攻", "法治至上"], answer: 0, explanation: "四端說正是孟子性善論的重要內容。", diff: 2 },
      { id: "jtsem2-079", source: "論四端", type: "語句理解", question: "「若火之始然，泉之始達」的比喻最想說明甚麼？", options: ["善端雖微，卻可發展壯大", "人心十分脆弱易滅", "仁義像水火般對立", "善性只在少數人身上"], answer: 0, explanation: "初燃之火、初達之泉都象徵善端一經培養便可擴大。", diff: 4 },
      { id: "jtsem2-080", source: "論四端", type: "賞析", question: "《論四端》最終要說服讀者的，不只是人有善端，而更是甚麼？", options: ["善端必須實踐與擴充", "善端不需理會", "善端只屬理論", "善端能代替一切制度"], answer: 0, explanation: "孟子不是停留在「有」，而是強調進一步「充之」。", diff: 4 },

      { id: "jtsem2-081", source: "大同與小康", type: "內容理解", question: "《大同與小康》中，孔子最嚮往的是哪一種社會？", options: ["大同", "小康", "亂世", "霸政"], answer: 0, explanation: "文中指出孔子最崇尚的是大同世界。", diff: 1 },
      { id: "jtsem2-082", source: "大同與小康", type: "內容理解", question: "大同社會最核心的政治原則是甚麼？", options: ["天下為公", "天下為家", "貨力為己", "大人世及"], answer: 0, explanation: "「天下為公」是大同社會的核心特徵。", diff: 1 },
      { id: "jtsem2-083", source: "大同與小康", type: "內容理解", question: "「選賢與能，講信修睦」屬於哪一種社會的描述？", options: ["大同", "小康", "亂世", "戰國"], answer: 0, explanation: "這是大同社會中的政治與人際理想。", diff: 1 },
      { id: "jtsem2-084", source: "大同與小康", type: "內容理解", question: "「不獨親其親，不獨子其子」最能體現大同社會甚麼精神？", options: ["推己及人", "嚴守家族界限", "重視私有財產", "崇尚武力競爭"], answer: 0, explanation: "不只愛自己親人，也把關愛推廣到他人。", diff: 2 },
      { id: "jtsem2-085", source: "大同與小康", type: "內容理解", question: "「矜、寡、孤、獨、廢疾者皆有所養」主要說明大同社會重視甚麼？", options: ["弱勢照顧", "軍事訓練", "商業繁榮", "家族繼承"], answer: 0, explanation: "這句突出理想社會對各類弱勢者的照顧。", diff: 2 },
      { id: "jtsem2-086", source: "大同與小康", type: "內容理解", question: "「貨，惡其棄於地也，不必藏於己」表現大同社會怎樣的價值？", options: ["珍惜物資而不私藏", "追求財富壟斷", "鼓勵浪費享樂", "重視家族積聚"], answer: 0, explanation: "人們珍惜勞動成果，但不一定據為己有。", diff: 2 },
      { id: "jtsem2-087", source: "大同與小康", type: "內容理解", question: "「力，惡其不出於身也，不必為己」一句主要說明甚麼？", options: ["人樂於貢獻勞力，不只為私利", "人們工作全為個人財富", "社會禁止勞動", "人人依賴別人養活"], answer: 0, explanation: "大同社會中，人們願意出力，不只為自己。", diff: 2 },
      { id: "jtsem2-088", source: "大同與小康", type: "內容理解", question: "「外戶而不閉」反映了大同社會哪方面的情況？", options: ["社會治安極好", "家家貧窮無物", "人人離鄉別井", "禮制十分森嚴"], answer: 0, explanation: "因為沒有盜賊，所以外門不用關閉。", diff: 2 },
      { id: "jtsem2-089", source: "大同與小康", type: "內容理解", question: "小康社會的最基本特徵是甚麼？", options: ["天下為家", "天下為公", "外戶不閉", "謀閉不興"], answer: 0, explanation: "小康與大同不同，其特點是「天下為家」。", diff: 1 },
      { id: "jtsem2-090", source: "大同與小康", type: "內容理解", question: "小康社會中，人們較重視甚麼？", options: ["個人與家族利益", "天下公義共享", "無私奉獻勞力", "人人平等無分"], answer: 0, explanation: "「各親其親，各子其子；貨力為己」正表現此點。", diff: 2 },
      { id: "jtsem2-091", source: "大同與小康", type: "內容理解", question: "小康社會容易出現甚麼問題？", options: ["陰謀與戰爭", "完全無爭", "外戶不閉", "人人無私"], answer: 0, explanation: "文中說「謀用是作，而兵由此起」。", diff: 2 },
      { id: "jtsem2-092", source: "大同與小康", type: "內容理解", question: "在小康社會中，君主主要靠甚麼維持秩序？", options: ["禮義與制度", "武力掠奪", "完全放任", "取消名分"], answer: 0, explanation: "文中指出以禮義為紀，以設制度，以立田里。", diff: 3 },
      { id: "jtsem2-093", source: "大同與小康", type: "比較理解", question: "下列哪一項不屬於大同社會特徵？", options: ["天下為家", "選賢與能", "講信修睦", "外戶不閉"], answer: 0, explanation: "「天下為家」是小康社會的特徵。", diff: 2 },
      { id: "jtsem2-094", source: "大同與小康", type: "比較理解", question: "下列哪一項最能概括大同與小康的關係？", options: ["前者是最高理想，後者是退而求其次的秩序", "前者低於後者", "兩者完全相同", "兩者都只講私利"], answer: 0, explanation: "孔子最崇尚大同，至不得已才期望有小康。", diff: 3 },
      { id: "jtsem2-095", source: "大同與小康", type: "主旨", question: "《大同與小康》主要說明甚麼？", options: ["理想社會與現實秩序的兩種層次", "戰亂中的送別痛苦", "宮市對百姓的剝削", "鄉村生活的拙樸美"], answer: 0, explanation: "文章通過大同與小康對照，說明社會理想與次一層秩序。", diff: 3 },
      { id: "jtsem2-096", source: "大同與小康", type: "深層理解", question: "孔子先說大同，再說小康，這樣安排最主要的作用是甚麼？", options: ["形成理想與現實的層次對照", "使文章更有節奏而已", "避免重複用詞", "表現作者遊觀心情"], answer: 0, explanation: "先立最高理想，再說現實可維持之秩序，對比鮮明。", diff: 4 },
      { id: "jtsem2-097", source: "大同與小康", type: "價值理解", question: "若用一句話概括大同社會，下列哪項最恰當？", options: ["以公義和和睦為本的理想社會", "以私利與競爭為本的社會", "以戰功和擴張為本的社會", "以享樂和奢侈為本的社會"], answer: 0, explanation: "大同社會重公義、誠信、和睦與共享。", diff: 3 },
      { id: "jtsem2-098", source: "大同與小康", type: "內容理解", question: "「男有分，女有歸」一句主要說明甚麼？", options: ["社會秩序分工井然", "男女地位完全相同", "女子地位高於男子", "人人不受任何規範"], answer: 0, explanation: "這句強調社會中男女各有其角色與安頓。", diff: 3 },
      { id: "jtsem2-099", source: "大同與小康", type: "內容理解", question: "《大同與小康》中，孔子「喟然而歎」的直接原因是甚麼？", options: ["感嘆魯國禮義衰落", "感傷與友人離別", "憂心戰敗慘重", "羨慕田園生活"], answer: 0, explanation: "文章開頭交代孔子之歎，蓋歎魯也。", diff: 2 },
      { id: "jtsem2-100", source: "大同與小康", type: "賞析", question: "《大同與小康》最值得注意的特色之一是甚麼？", options: ["透過比較展示價值判斷", "以大量人物對話取勝", "以場面描寫為主", "以戲劇衝突見長"], answer: 0, explanation: "文章不是單寫一種社會，而是用對比凸顯價值層次。", diff: 4 },

      { id: "jtsem2-101", source: "悲陳陶", type: "文言字詞", question: "《悲陳陶》中「十郡良家子」的「良家子」是指哪一類人？", options: ["普通人家子弟", "豪門貴族子弟", "宮廷侍從", "邊地胡人"], answer: 0, explanation: "「良家子」多指平民百姓家的子弟，突顯戰死者並非特權階層。", diff: 2 },
      { id: "jtsem2-102", source: "悲陳陶", type: "內容理解", question: "《悲陳陶》主要描寫甚麼？", options: ["戰敗後極其慘烈的景象", "田園閒適生活", "送別友人的場面", "宮市剝削百姓"], answer: 0, explanation: "全詩重在悲悼陳陶之戰後義軍大批戰死的景象。", diff: 2 },
      { id: "jtsem2-103", source: "悲陳陶", type: "內容理解", question: "「血作陳陶澤」一句主要有何作用？", options: ["突出死傷之多與戰況慘烈", "描寫澤地顏色鮮紅", "說明陳陶土地肥沃", "歌頌義軍英勇"], answer: 0, explanation: "以極沉痛的誇飾方式，突顯戰死人數眾多。", diff: 3 },
      { id: "jtsem2-104", source: "悲陳陶", type: "內容理解", question: "「四萬義軍同日死」最主要帶來甚麼效果？", options: ["強化數量與震撼感", "顯示軍隊實力龐大", "表示義軍自願殉國", "說明戰鬥時間很短"], answer: 0, explanation: "具體數字令戰敗與死亡之慘更具衝擊力。", diff: 3 },
      { id: "jtsem2-105", source: "悲陳陶", type: "文言字詞", question: "「野曠天清無戰聲」中的「曠」最接近哪一項意思？", options: ["空闊", "荒謬", "久遠", "遲慢"], answer: 0, explanation: "「野曠」是曠野空闊之意。", diff: 2 },
      { id: "jtsem2-106", source: "悲陳陶", type: "賞析", question: "《悲陳陶》中「無戰聲」與「同日死」並列，有何藝術效果？", options: ["以寂靜反襯慘烈", "轉入閒適氣氛", "顯示戰事勝利後平靜", "說明戰場本來很安寧"], answer: 0, explanation: "戰後的空寂更襯出先前死傷之慘。", diff: 4 },
      { id: "jtsem2-107", source: "悲陳陶", type: "思想感情", question: "《悲陳陶》的主要感情基調是甚麼？", options: ["悲憤哀痛", "輕鬆閒適", "欣喜歡騰", "幽默諷刺"], answer: 0, explanation: "題中已標「悲」，全詩亦以哀悼與沉痛為主。", diff: 2 },
      { id: "jtsem2-108", source: "悲陳陶", type: "主旨", question: "《悲陳陶》的主旨最接近哪一項？", options: ["哀悼戰死將士並控訴戰爭殘酷", "描寫自然景色清幽", "歌頌軍隊凱旋", "表達閒居之樂"], answer: 0, explanation: "此詩透過對義軍戰死的描寫，強烈表現戰爭之慘。", diff: 4 },
      { id: "jtsem2-109", source: "悲陳陶", type: "文言字詞", question: "《悲陳陶》中的「同日死」應如何理解？", options: ["在同一天大量陣亡", "同一天出生", "同一天出發", "同一天凱旋"], answer: 0, explanation: "此句強調死亡集中於同一日，更見戰敗慘重。", diff: 2 },
      { id: "jtsem2-110", source: "悲陳陶", type: "深層理解", question: "《悲陳陶》不只是在寫死亡場面，更在寫甚麼？", options: ["戰爭如何吞噬無數普通生命", "詩人個人的邊塞旅行", "將軍建立赫赫戰功", "敵軍的狡猾詭計"], answer: 0, explanation: "「良家子」的設定，使死亡不只是軍事事件，更是人民命運的悲劇。", diff: 5 },

      { id: "jtsem2-111", source: "賣炭翁", type: "內容理解", question: "《賣炭翁》中，賣炭翁以甚麼維生？", options: ["伐薪燒炭", "耕田種米", "捕魚販鹽", "紡織賣布"], answer: 0, explanation: "詩開首便說「伐薪燒炭南山中」。", diff: 1 },
      { id: "jtsem2-112", source: "賣炭翁", type: "人物描寫", question: "「滿面塵灰煙火色，兩鬢蒼蒼十指黑」主要有何作用？", options: ["刻畫賣炭翁勞苦辛酸的形象", "描寫山林景色壯麗", "表現宮使威風八面", "渲染市集熱鬧"], answer: 0, explanation: "這是典型外貌描寫，用極少筆墨寫盡勞動之苦。", diff: 2 },
      { id: "jtsem2-113", source: "賣炭翁", type: "內容理解", question: "「可憐身上衣正單，心憂炭賤願天寒」反映賣炭翁怎樣的心理？", options: ["為生計所逼而產生矛盾願望", "喜歡寒冷天氣", "不怕寒冷勞作", "討厭賣炭工作"], answer: 0, explanation: "自己衣單受寒，卻又盼天冷使炭價上升，極具悲劇性。", diff: 3 },
      { id: "jtsem2-114", source: "賣炭翁", type: "內容理解", question: "奪走炭車的是甚麼人？", options: ["黃衣使者白衫兒", "村中里正", "路過商人", "山中樵夫"], answer: 0, explanation: "詩中明言來者是宮使及其隨從。", diff: 1 },
      { id: "jtsem2-115", source: "賣炭翁", type: "文言字詞", question: "「手把文書口稱敕」中的「敕」是指甚麼？", options: ["皇帝命令", "地方公文", "買賣契約", "軍中號令"], answer: 0, explanation: "「敕」是皇帝詔令，宮使借此假傳權勢。", diff: 2 },
      { id: "jtsem2-116", source: "賣炭翁", type: "內容理解", question: "宮使奪炭時給了賣炭翁甚麼？", options: ["半疋紅紗一丈綾", "一大袋銀兩", "滿車糧食", "官府賞銀"], answer: 0, explanation: "這點可笑而沉痛的「報酬」正突顯宮市的剝削。", diff: 1 },
      { id: "jtsem2-117", source: "賣炭翁", type: "文言字詞", question: "「一車炭重千餘斤，宮使驅將惜不得」中的「惜不得」最接近哪一項？", options: ["雖可惜卻不得不放手", "十分珍惜地保存", "不覺得可惜", "高興地送給別人"], answer: 0, explanation: "此句寫出面對強權時的萬般不捨與無可奈何。", diff: 3 },
      { id: "jtsem2-118", source: "賣炭翁", type: "主旨", question: "《賣炭翁》的主旨最接近哪一項？", options: ["揭露宮市對百姓的剝削", "讚美勞動創造幸福", "描寫冬日雪景之美", "歌頌宮廷賞賜豐厚"], answer: 0, explanation: "白居易藉此詩深刻揭露宮市害民。", diff: 3 },
      { id: "jtsem2-119", source: "賣炭翁", type: "寫作手法", question: "《賣炭翁》最主要的寫作特色之一是甚麼？", options: ["白描直敘，含蓄見深意", "大量鋪寫典故", "重神怪幻想", "偏重駢儷辭藻"], answer: 0, explanation: "作者用平實直接的敘述，反令讀者更深刻感受其苦。", diff: 4 },
      { id: "jtsem2-120", source: "賣炭翁", type: "深層理解", question: "《賣炭翁》最令人震撼的地方，不只是老翁之苦，而更在於甚麼？", options: ["制度本身以權勢名義進行掠奪", "老翁年紀很大還工作", "天氣十分寒冷", "炭車實在太重"], answer: 0, explanation: "作品批判的不只是個人不幸，而是制度化的剝削。", diff: 5 },

      { id: "jtsem2-121", source: "沉醉東風・送別", type: "元曲格律", question: "《沉醉東風・送別》所屬的文體是甚麼？", options: ["散曲小令", "近體詩", "駢文", "古文"], answer: 0, explanation: "《沉醉東風》是曲牌名，屬元曲中的散曲小令。", diff: 1 },
      { id: "jtsem2-122", source: "沉醉東風・送別", type: "內容理解", question: "《沉醉東風・送別》的核心情感是甚麼？", options: ["離別不捨", "憂國傷時", "閒居自得", "戰亂悲憤"], answer: 0, explanation: "全曲圍繞送別場景，重點在依依惜別。", diff: 1 },
      { id: "jtsem2-123", source: "沉醉東風・送別", type: "內容理解", question: "「手執着餞行杯，眼擱着別離淚」主要描寫甚麼？", options: ["送別時動作與神態", "戰場上的悲壯", "村中宴飲熱鬧", "朝廷宴會規模"], answer: 0, explanation: "此句以手、眼兩方面寫送別之情。", diff: 2 },
      { id: "jtsem2-124", source: "沉醉東風・送別", type: "內容理解", question: "「好去者望前程萬里」表面上表達甚麼？", options: ["祝福對方", "責備對方", "嘲笑對方", "命令對方"], answer: 0, explanation: "這是送別曲中常見的祝願語。", diff: 2 },
      { id: "jtsem2-125", source: "沉醉東風・送別", type: "深層理解", question: "「好去者望前程萬里」與「捨不得」並存，形成怎樣的情感特點？", options: ["祝福中帶不捨", "喜悅中帶憤怒", "平靜中帶疏離", "歡騰中帶嘲笑"], answer: 0, explanation: "送別作品常是既祝對方前程，又難捨離別。", diff: 3 },
      { id: "jtsem2-126", source: "沉醉東風・送別", type: "元曲格律", question: "元曲中，「沉醉東風」屬於哪一類名稱？", options: ["曲牌名", "作品題目類型", "宮廷官職", "押韻格式"], answer: 0, explanation: "「沉醉東風」是固定曲牌名，「送別」才是題目內容。", diff: 2 },
      { id: "jtsem2-127", source: "沉醉東風・送別", type: "內容理解", question: "《沉醉東風・送別》的語言風格較接近哪一項？", options: ["口語直白", "艱深冷僻", "典故繁密", "莊嚴肅穆"], answer: 0, explanation: "關漢卿曲作常具口語色彩，情感也較直接。", diff: 2 },
      { id: "jtsem2-128", source: "沉醉東風・送別", type: "元曲格律", question: "元曲相較於古文與古詩，常見的一個語言特點是甚麼？", options: ["口語化較強", "完全不用修辭", "必須對仗工整", "只能寫議論"], answer: 0, explanation: "元曲語言較接近日常口語，讀來更活潑流暢。", diff: 3 },
      { id: "jtsem2-129", source: "沉醉東風・送別", type: "賞析", question: "《沉醉東風・送別》之所以感人，關鍵較在於甚麼？", options: ["直率真切的送別情感", "戰爭場面的壯觀", "哲理議論的嚴密", "歷史掌故的豐富"], answer: 0, explanation: "這首曲動人之處在於直接而真切的離情。", diff: 3 },
      { id: "jtsem2-130", source: "沉醉東風・送別", type: "主旨", question: "《沉醉東風・送別》最適合作為哪一類作品的代表？", options: ["元曲送別抒情作品", "邊塞反戰詩", "儒家說理文", "田園散文"], answer: 0, explanation: "此曲集中寫送別之情，最具送別元曲特色。", diff: 2 },

      { id: "jtsem2-131", source: "四塊玉・閒適（其一）", type: "元曲格律", question: "《四塊玉》屬於甚麼？", options: ["曲牌名", "篇章題目", "文言虛詞", "古詩體例"], answer: 0, explanation: "《四塊玉》是元曲曲牌名。", diff: 1 },
      { id: "jtsem2-132", source: "四塊玉・閒適（其一）", type: "內容理解", question: "《四塊玉・閒適》其一主要展現哪種生活情趣？", options: ["樸素共享的閒居之樂", "戰敗後的哀傷", "送別時的淒楚", "仕途受挫的憤恨"], answer: 0, explanation: "曲中透過飲食與相聚，寫出閒適自得。", diff: 1 },
      { id: "jtsem2-133", source: "四塊玉・閒適（其一）", type: "內容理解", question: "「他出一對雞，我出一個鵝」最能表現甚麼？", options: ["樸素而熱鬧的共享生活", "奢華宴會的排場", "商業交易的精明", "生活困乏無以為繼"], answer: 0, explanation: "簡單食材卻充滿情味，正顯閒居之樂。", diff: 2 },
      { id: "jtsem2-134", source: "四塊玉・閒適（其一）", type: "內容理解", question: "《四塊玉・閒適》其一的整體情感基調最接近哪一項？", options: ["閒逸快活", "沉痛悲憤", "依依惜別", "憂國憂民"], answer: 0, explanation: "作品充滿日常相聚與自得其樂的氣息。", diff: 1 },
      { id: "jtsem2-135", source: "四塊玉・閒適（其一）", type: "元曲格律", question: "元曲小令常有一個特色，就是甚麼？", options: ["篇幅短而節奏鮮明", "必定字數整齊如律詩", "只能用文言虛詞構成", "完全不用押韻"], answer: 0, explanation: "元曲小令篇幅較短，節奏與曲調感都很鮮明。", diff: 2 },
      { id: "jtsem2-136", source: "四塊玉・閒適（其一）", type: "賞析", question: "《四塊玉・閒適》其一之所以有趣，關鍵在於甚麼？", options: ["把日常小事寫得生動有味", "刻意追求華麗辭藻", "以長篇議論說理", "重複鋪陳戰場場面"], answer: 0, explanation: "這首曲的魅力在於生活化而有畫面感。", diff: 3 },
      { id: "jtsem2-137", source: "四塊玉・閒適（其一）", type: "主旨", question: "《四塊玉・閒適》其一最主要是在歌詠甚麼？", options: ["平凡生活中的閒適樂趣", "邊塞征戰精神", "離別後的惆悵", "朝廷制度之美"], answer: 0, explanation: "從日常飲食與相聚中，表現一種樸實生活的可貴。", diff: 3 },
      { id: "jtsem2-138", source: "四塊玉・閒適（其一）", type: "內容理解", question: "作品中的閒適並不等於甚麼？", options: ["奢華鋪張", "自然自在", "朋友共享", "心境放鬆"], answer: 0, explanation: "此曲重閒適，不重奢侈。", diff: 2 },
      { id: "jtsem2-139", source: "四塊玉・閒適（其一）", type: "元曲格律", question: "元曲中，題目常由「曲牌名＋題目」構成，例如《四塊玉・閒適》，其中「閒適」是甚麼？", options: ["題目", "曲牌", "宮調", "韻部"], answer: 0, explanation: "《四塊玉》是曲牌名，「閒適」是題目。", diff: 2 },
      { id: "jtsem2-140", source: "四塊玉・閒適（其一）", type: "深層理解", question: "《四塊玉・閒適》其一的價值不只在寫吃喝，而更在於甚麼？", options: ["寫出人與人之間自然相處的快樂", "宣揚享樂主義", "批評世道艱難", "強調功名重要"], answer: 0, explanation: "作品真正可貴的是共享、閒樂與自然人情。", diff: 4 },

      { id: "jtsem2-141", source: "四塊玉・閒適（其二）", type: "內容理解", question: "《四塊玉・閒適》其二中，「賢的是他，愚的是我，爭甚麼」主要表達甚麼？", options: ["看淡是非高下", "強烈自卑感", "對朋友不滿", "渴望功名比較"], answer: 0, explanation: "這句表明作者對世俗賢愚之辨採取超脫態度。", diff: 2 },
      { id: "jtsem2-142", source: "四塊玉・閒適（其二）", type: "思想感情", question: "《四塊玉・閒適》其二的情感基調最接近哪一項？", options: ["達觀超脫", "激憤不平", "離愁別緒", "憂國沉痛"], answer: 0, explanation: "作者經歷世態後，更顯看淡與超然。", diff: 2 },
      { id: "jtsem2-143", source: "四塊玉・閒適（其二）", type: "內容理解", question: "「世態人情經歷多」一句最能作為下文哪種態度的原因？", options: ["看透爭競，轉而自適", "立志報國，從軍邊塞", "一心求仕，積極進取", "哀嘆家貧，悲傷不已"], answer: 0, explanation: "因為看透世態人情，所以不再執著爭競。", diff: 3 },
      { id: "jtsem2-144", source: "四塊玉・閒適（其二）", type: "元曲格律", question: "《四塊玉・閒適》其一與其二同用一個曲牌，這說明甚麼？", options: ["曲牌固定，題材內容可不同", "兩首內容一定相同", "字數必定完全一致而不可變", "只能寫戰爭主題"], answer: 0, explanation: "曲牌規定的是格律框架，內容主題可以不同。", diff: 3 },
      { id: "jtsem2-145", source: "四塊玉・閒適（其二）", type: "賞析", question: "《四塊玉・閒適》其二較其一更偏向甚麼？", options: ["人生態度的表達", "具體飲食描寫", "戰爭場景鋪陳", "送別動作刻畫"], answer: 0, explanation: "其二較偏重經歷世態後的達觀心境。", diff: 3 },
      { id: "jtsem2-146", source: "四塊玉・閒適（其二）", type: "內容理解", question: "「爭甚麼」一句表面是問句，實際更接近哪種語氣？", options: ["反詰", "哀求", "命令", "祝願"], answer: 0, explanation: "此句不是求答案，而是反詰式表明無須爭競。", diff: 3 },
      { id: "jtsem2-147", source: "四塊玉・閒適（其二）", type: "主旨", question: "《四塊玉・閒適》其二主要表現甚麼？", options: ["經歷世態後的淡泊與自適", "對戰場死傷的哀悼", "送別情人的苦楚", "對宮市害民的控訴"], answer: 0, explanation: "其二的重點在於經歷人情世態後的超脫態度。", diff: 3 },
      { id: "jtsem2-148", source: "四塊玉・閒適（其二）", type: "元曲格律", question: "元曲常見「俗中見雅」的特色，《四塊玉・閒適》其二最能體現在哪裡？", options: ["用通俗語言表達深的人生感悟", "大量典故堆砌", "句句皆用對偶", "完全不用口語"], answer: 0, explanation: "作品語言不艱深，卻能表達深刻的人生態度。", diff: 4 },
      { id: "jtsem2-149", source: "四塊玉・閒適（其二）", type: "深層理解", question: "《四塊玉・閒適》其二並非消極厭世，而更接近哪一項？", options: ["看透後的從容", "徹底絕望", "冷酷無情", "完全放棄與人來往"], answer: 0, explanation: "作者並非悲觀，而是對世俗榮辱有更淡然的態度。", diff: 4 },
      { id: "jtsem2-150", source: "四塊玉・閒適（其二）", type: "對讀比較", question: "《四塊玉・閒適》其一與其二相比，最恰當的理解是甚麼？", options: ["前者重生活閒樂，後者重心境達觀", "前者重達觀，後者重送別", "兩者都專寫戰亂", "兩者皆重朝廷制度"], answer: 0, explanation: "其一偏日常生活，其二偏人生態度，都是閒適但層次不同。", diff: 4 },

      { id: "jtsem2-151", source: "天淨沙・魯卿庵中", type: "元曲格律", question: "《天淨沙》在元曲中屬於甚麼？", options: ["曲牌名", "題目名稱", "詩體名稱", "散文篇名"], answer: 0, explanation: "《天淨沙》是曲牌名，「魯卿庵中」是題目或題旨。", diff: 1 },
      { id: "jtsem2-152", source: "天淨沙・魯卿庵中", type: "內容理解", question: "《天淨沙・魯卿庵中》整體營造的氣氛較接近哪一項？", options: ["清幽淡遠", "悲憤沉痛", "熱鬧繁華", "慷慨激昂"], answer: 0, explanation: "作品以簡練景語營造出幽靜清遠的意境。", diff: 1 },
      { id: "jtsem2-153", source: "天淨沙・魯卿庵中", type: "內容理解", question: "「青苔古木」主要營造哪種感覺？", options: ["幽靜古雅", "熱烈燦爛", "華美壯觀", "荒涼可怖"], answer: 0, explanation: "青苔與古木常帶出靜謐、古雅的氣息。", diff: 2 },
      { id: "jtsem2-154", source: "天淨沙・魯卿庵中", type: "內容理解", question: "「紅葉山齋小小」一句最主要作用是甚麼？", options: ["點出景致精巧幽雅", "渲染兵荒馬亂", "表現離別痛楚", "說明居所破敗"], answer: 0, explanation: "這句寫出秋色中小齋的雅致與靜美。", diff: 2 },
      { id: "jtsem2-155", source: "天淨沙・魯卿庵中", type: "內容理解", question: "「探梅人過溪橋」為畫面加入了甚麼？", options: ["一點動態與人文氣息", "戰爭殺伐感", "喧鬧市集感", "濃厚離情"], answer: 0, explanation: "在靜景中加入人影，使整體更有層次與雅趣。", diff: 3 },
      { id: "jtsem2-156", source: "天淨沙・魯卿庵中", type: "元曲格律", question: "《天淨沙・魯卿庵中》最能體現元曲哪一項特色？", options: ["用極少筆墨造成鮮明境界", "以長篇論證說理", "重用史事典故展開", "句句必成對偶"], answer: 0, explanation: "元曲小令篇幅短，卻能以精簡景語造境。", diff: 3 },
      { id: "jtsem2-157", source: "天淨沙・魯卿庵中", type: "主旨", question: "《天淨沙・魯卿庵中》主要表現甚麼？", options: ["清幽閒雅的山居情味", "戰爭對百姓的傷害", "送別友人的哀傷", "宮廷生活的奢華"], answer: 0, explanation: "全曲重在營造山齋幽境與閒雅情趣。", diff: 2 },
      { id: "jtsem2-158", source: "天淨沙・魯卿庵中", type: "賞析", question: "此曲之所以耐人尋味，最關鍵在於甚麼？", options: ["景物少而意境深", "故事曲折離奇", "人物衝突強烈", "議論十分嚴密"], answer: 0, explanation: "這首小令可謂字少境深，以簡見豐。", diff: 3 },
      { id: "jtsem2-159", source: "天淨沙・魯卿庵中", type: "元曲格律", question: "元曲中常見「曲牌名＋題目」，在《天淨沙・魯卿庵中》中，「魯卿庵中」屬於哪一部分？", options: ["題目", "曲牌", "宮調", "韻腳"], answer: 0, explanation: "《天淨沙》是曲牌，「魯卿庵中」是題目。", diff: 2 },
      { id: "jtsem2-160", source: "天淨沙・魯卿庵中", type: "深層理解", question: "《天淨沙・魯卿庵中》所呈現的，不只是景色之美，更是一種甚麼？", options: ["心境之靜", "報國之志", "控訴之情", "離散之痛"], answer: 0, explanation: "景之幽，正對應作者內在的閒靜與淡遠。", diff: 4 },

      { id: "jtsem2-161", source: "端正好・長亭送別", type: "元曲格律", question: "《端正好》在作品名稱中屬於甚麼？", options: ["曲牌名", "題目", "文體", "句式"], answer: 0, explanation: "《端正好》是曲牌名，「長亭送別」是題目。", diff: 1 },
      { id: "jtsem2-162", source: "端正好・長亭送別", type: "內容理解", question: "「碧雲天，黃花地，西風緊，北雁南飛」主要作用是甚麼？", options: ["借秋景渲染離愁", "描寫戰場肅殺", "表現村居閒適", "鋪陳宮廷華麗"], answer: 0, explanation: "這組景語典型地以秋景襯托送別之情。", diff: 2 },
      { id: "jtsem2-163", source: "端正好・長亭送別", type: "修辭手法", question: "「曉來誰染霜林醉？總是離人淚」最明顯運用了哪種修辭效果？", options: ["設問兼情景交融", "借代兼用典", "頂真兼排比", "互文兼反問"], answer: 0, explanation: "先問後答，又把霜林與離人淚融為一體。", diff: 3 },
      { id: "jtsem2-164", source: "端正好・長亭送別", type: "內容理解", question: "「總是離人淚」一句把甚麼連結起來？", options: ["景物與離情", "戰爭與功名", "村居與農事", "義理與制度"], answer: 0, explanation: "此句最典型地體現了情景交融。", diff: 2 },
      { id: "jtsem2-165", source: "端正好・長亭送別", type: "內容理解", question: "《端正好・長亭送別》的核心情感是甚麼？", options: ["離別哀傷", "閒逸自樂", "憂國憤世", "民生苦難"], answer: 0, explanation: "全曲以長亭送別為題，重點自然在離愁。", diff: 1 },
      { id: "jtsem2-166", source: "端正好・長亭送別", type: "元曲格律", question: "《端正好・長亭送別》最能代表元曲哪一項特色？", options: ["景語集中而情味濃", "必須對仗整齊", "以長篇說理見長", "只能寫歷史題材"], answer: 0, explanation: "元曲擅長以簡潔景語傳達濃烈情感。", diff: 3 },
      { id: "jtsem2-167", source: "端正好・長亭送別", type: "賞析", question: "「碧雲天，黃花地」之所以動人，關鍵不在景物本身，而在於甚麼？", options: ["景中含情", "典故豐富", "語意艱深", "情節複雜"], answer: 0, explanation: "景物之美因承載離愁而特別動人。", diff: 3 },
      { id: "jtsem2-168", source: "端正好・長亭送別", type: "內容理解", question: "「北雁南飛」常帶有哪種意象作用？", options: ["加深秋意與離情", "象徵凱旋而歸", "表示城市繁榮", "暗示農事豐收"], answer: 0, explanation: "雁南飛常與秋意、遠行、離別相聯。", diff: 2 },
      { id: "jtsem2-169", source: "端正好・長亭送別", type: "主旨", question: "《端正好・長亭送別》最主要在寫甚麼？", options: ["送別中的秋景與離愁", "田園中的閒情與樂趣", "義軍戰死的悲哀", "宮使奪炭的無理"], answer: 0, explanation: "此曲以秋日長亭送別為核心情境。", diff: 2 },
      { id: "jtsem2-170", source: "端正好・長亭送別", type: "深層理解", question: "《端正好・長亭送別》最見功力之處在於甚麼？", options: ["以極凝練的景語承載濃厚情感", "以冗長敘事交代背景", "以議論直接說理", "以人物對話推進劇情"], answer: 0, explanation: "這首曲篇幅不長，卻能以景語寫盡離情。", diff: 4 },

      { id: "jtsem2-171", source: "元曲四首對讀", type: "對讀比較", question: "《沉醉東風・送別》與《端正好・長亭送別》共同的主題是甚麼？", options: ["送別離情", "田園閒樂", "戰亂民苦", "理想政治"], answer: 0, explanation: "兩篇都以送別為主，只是表現方式不同。", diff: 2 },
      { id: "jtsem2-172", source: "元曲四首對讀", type: "對讀比較", question: "《沉醉東風・送別》與《端正好・長亭送別》相比，前者更偏重甚麼？", options: ["直接口語抒情", "秋景鋪排", "戰場描寫", "義理論證"], answer: 0, explanation: "《沉醉東風》語言較直白，感情表達也更直接。", diff: 3 },
      { id: "jtsem2-173", source: "元曲四首對讀", type: "對讀比較", question: "《端正好・長亭送別》與《沉醉東風・送別》相比，前者更偏重甚麼？", options: ["借景渲染離愁", "具體飲食場景", "看淡賢愚之辨", "靜寫山居幽景"], answer: 0, explanation: "《端正好》最突出的正是秋景與離情相融。", diff: 3 },
      { id: "jtsem2-174", source: "元曲四首對讀", type: "對讀比較", question: "《四塊玉・閒適》兩首與《天淨沙・魯卿庵中》的共同點是甚麼？", options: ["都帶有閒適幽雅情趣", "都以送別為核心", "都在控訴戰爭", "都以議論為主"], answer: 0, explanation: "它們都偏向閒逸、幽靜與淡遠的人生／審美情趣。", diff: 2 },
      { id: "jtsem2-175", source: "元曲四首對讀", type: "對讀比較", question: "《四塊玉・閒適》其一與其二最主要的差別是甚麼？", options: ["前者重生活情趣，後者重人生態度", "前者寫送別，後者寫戰爭", "前者重義理，後者重景色", "兩者完全無差別"], answer: 0, explanation: "其一具體寫閒居日常，其二偏向看透世態後的達觀。", diff: 3 },
      { id: "jtsem2-176", source: "元曲四首對讀", type: "對讀比較", question: "《天淨沙・魯卿庵中》與《端正好・長亭送別》都善用景語，但主要差別在哪裡？", options: ["前者偏靜境，後者偏離愁", "前者寫戰事，後者寫閒居", "前者口語，後者說理", "前者典故多，後者全白話"], answer: 0, explanation: "前者營造清幽之境，後者借秋景渲染送別之情。", diff: 4 },
      { id: "jtsem2-177", source: "元曲四首對讀", type: "元曲格律", question: "元曲四首都可用來說明哪一項文體特色？", options: ["曲牌固定而題旨可變", "字數必定與律詩相同", "只能使用典故", "完全沒有口語色彩"], answer: 0, explanation: "元曲可在同一曲牌下寫不同題旨，且語言風格靈活。", diff: 4 },
      { id: "jtsem2-178", source: "元曲四首對讀", type: "內容理解", question: "如果把元曲四首分成兩組，最合理的分法是甚麼？", options: ["送別兩首、閒適兩首", "戰爭兩首、政治兩首", "散文兩首、詩歌兩首", "文言兩首、白話兩首"], answer: 0, explanation: "《沉醉東風》《端正好》屬送別，《四塊玉》與《天淨沙》偏閒適。", diff: 3 },
      { id: "jtsem2-179", source: "元曲四首對讀", type: "賞析", question: "元曲四首整體最能展現元曲甚麼特色？", options: ["短小而情景鮮明", "冗長而議論嚴密", "句式呆板固定", "只適合寫政治"], answer: 0, explanation: "四首都可見元曲篇幅短而畫面與情感鮮明的特色。", diff: 3 },
      { id: "jtsem2-180", source: "元曲四首對讀", type: "深層理解", question: "元曲四首共同的文學價值，最適合概括為甚麼？", options: ["以凝練語言承載豐富情感與意境", "以史事考證為主", "以哲學說理取勝", "以軍事紀錄見長"], answer: 0, explanation: "無論送別或閒適，元曲都善於用短句表情造境。", diff: 4 },

      { id: "jtsem2-181", source: "悲陳陶・賣炭翁對讀", type: "對讀比較", question: "《悲陳陶》與《賣炭翁》的共同點最接近哪一項？", options: ["都關注普通人的苦難", "都寫送別之情", "都重山居幽景", "都談人性善端"], answer: 0, explanation: "一寫戰死義軍，一寫受剝削老翁，焦點都在人民。", diff: 3 },
      { id: "jtsem2-182", source: "悲陳陶・賣炭翁對讀", type: "對讀比較", question: "《悲陳陶》與《賣炭翁》最大的題材差異是甚麼？", options: ["前者寫戰爭死傷，後者寫宮市剝削", "前者寫送別，後者寫閒居", "前者寫理想社會，後者寫現代城市", "前者寫山水，後者寫女子"], answer: 0, explanation: "兩篇同樣寫民苦，但一是戰爭，一是制度性掠奪。", diff: 3 },
      { id: "jtsem2-183", source: "悲陳陶・賣炭翁對讀", type: "寫作手法", question: "《悲陳陶》與《賣炭翁》在表現手法上的共同點是甚麼？", options: ["都以具體細節凸顯深重悲劇", "都以大量議論為主", "都用神怪幻想推進情節", "都只寫景不寫人"], answer: 0, explanation: "血作陳陶澤、半疋紅紗一丈綾，都是極有力的細節。", diff: 4 },
      { id: "jtsem2-184", source: "悲陳陶・賣炭翁對讀", type: "文言字詞", question: "若從文言詞語考核看，《悲陳陶》與《賣炭翁》共同適合訓練哪一種能力？", options: ["結合語境理解詞義", "辨認現代白話俚語", "翻譯外來語", "分析數學術語"], answer: 0, explanation: "兩篇都適合透過語境理解「良家子」「敕」「惜不得」等詞義。", diff: 3 },
      { id: "jtsem2-185", source: "悲陳陶・賣炭翁對讀", type: "主旨理解", question: "若把《悲陳陶》與《賣炭翁》放在同一單元，最適合的主題是甚麼？", options: ["亂世與制度下的人民苦難", "送別與思鄉", "田園與閒情", "性善與禮治"], answer: 0, explanation: "兩篇都在不同角度呈現人民被壓迫與受害。", diff: 4 },
      { id: "jtsem2-186", source: "悲陳陶・賣炭翁對讀", type: "深層理解", question: "《悲陳陶》與《賣炭翁》最能共同說明哪一點？", options: ["文學可揭露時代與制度的殘酷", "文學只用來描寫風景", "百姓苦難與政治無關", "詩歌只適合抒情"], answer: 0, explanation: "兩篇都不只是個人悲傷，而是時代與制度問題的文學見證。", diff: 5 },

      { id: "jtsem2-187", source: "元曲四首", type: "元曲格律", question: "下列哪一項最能概括元曲的語言特色？", options: ["較接近日常口語", "只用艱深古字", "全以對偶句構成", "完全不用修辭"], answer: 0, explanation: "元曲語言較靈活，也常帶口語色彩。", diff: 2 },
      { id: "jtsem2-188", source: "元曲四首", type: "元曲格律", question: "元曲作品名稱常由甚麼組成？", options: ["曲牌名與題目", "作者名與年號", "體裁與章數", "宮調與韻腳"], answer: 0, explanation: "例如《端正好・長亭送別》、《天淨沙・魯卿庵中》皆如此。", diff: 2 },
      { id: "jtsem2-189", source: "元曲四首", type: "元曲格律", question: "同一曲牌是否只能寫同一內容？", options: ["不是，內容可不同", "是，主題完全固定", "只可寫送別", "只可寫閒適"], answer: 0, explanation: "曲牌規定格律框架，不限制唯一主題。", diff: 2 },
      { id: "jtsem2-190", source: "元曲四首", type: "元曲格律", question: "元曲小令在篇幅上通常有甚麼特點？", options: ["篇幅較短", "必定長於古文", "沒有固定句數概念", "每首都超過百句"], answer: 0, explanation: "元曲小令多篇幅短小，善於凝練表情達意。", diff: 1 },
      { id: "jtsem2-191", source: "元曲四首", type: "元曲格律", question: "元曲與詩歌相比，一個較常見的差別是甚麼？", options: ["語言更靈活活潑", "完全不用押韻", "不能寫景抒情", "不能表達哲理"], answer: 0, explanation: "元曲常具口語化與生活化特色。", diff: 3 },
      { id: "jtsem2-192", source: "元曲四首", type: "內容理解", question: "元曲四首中，哪兩首較偏重送別？", options: ["《沉醉東風・送別》與《端正好・長亭送別》", "《四塊玉》兩首", "《天淨沙》與《四塊玉》其二", "《天淨沙》與《端正好》"], answer: 0, explanation: "這兩首都明確以送別為核心。", diff: 2 },
      { id: "jtsem2-193", source: "元曲四首", type: "內容理解", question: "元曲四首中，哪幾首較偏重閒適？", options: ["《四塊玉》兩首與《天淨沙・魯卿庵中》", "《沉醉東風》與《端正好》", "只有《端正好》", "只有《沉醉東風》"], answer: 0, explanation: "《四塊玉》兩首與《天淨沙》都偏閒適幽雅。", diff: 2 },
      { id: "jtsem2-194", source: "元曲四首", type: "賞析", question: "元曲四首共同的藝術特點最接近哪一項？", options: ["以短篇幅造成鮮明境界", "以長敘事見長", "以史論說理為主", "句式全然整齊劃一"], answer: 0, explanation: "這幾首都篇幅不長，但極富畫面感與情味。", diff: 3 },
      { id: "jtsem2-195", source: "元曲四首", type: "深層理解", question: "元曲四首若作整體學習，最值得掌握的是甚麼？", options: ["曲牌、題旨與情景表達的關係", "朝代興亡的詳細史實", "兵法部署與戰術", "宮廷制度沿革"], answer: 0, explanation: "學習元曲，重點之一是理解曲牌與內容、情景的配合。", diff: 4 },
      { id: "jtsem2-196", source: "元曲四首", type: "主旨理解", question: "下列哪一句最能概括元曲四首的整體學習方向？", options: ["由曲牌入手，掌握格律特色與內容情感", "只需背誦題目，不必理解內容", "只需辨認作者，不必分析情感", "只需記住年代，不必留意語言"], answer: 0, explanation: "你指定的重點正是元曲格律與內容理解並重。", diff: 4 },

      { id: "jtsem2-197", source: "悲陳陶", type: "文言字詞", question: "《悲陳陶》中「義軍」一詞最接近哪一項？", options: ["以正義名義作戰的軍隊", "專門守城的軍隊", "運糧的部隊", "宮廷儀仗隊"], answer: 0, explanation: "「義軍」通常指以正義名義起兵或作戰的軍隊。", diff: 2 },
      { id: "jtsem2-198", source: "悲陳陶", type: "內容理解", question: "《悲陳陶》最能凸顯悲劇規模的地方是甚麼？", options: ["以大量死傷數字與血澤畫面強化震撼", "詳細記錄敵我兵器", "描寫大將表情", "描述凱旋盛況"], answer: 0, explanation: "數字與血澤意象共同把慘烈程度推高。", diff: 4 },
      { id: "jtsem2-199", source: "悲陳陶", type: "賞析", question: "《悲陳陶》比《兵車行》更集中寫哪一面？", options: ["戰後慘狀", "出征送別", "農村荒蕪", "租稅壓迫"], answer: 0, explanation: "《兵車行》較完整展開戰前與戰中民苦，《悲陳陶》更集中於戰後之悲。", diff: 4 },
      { id: "jtsem2-200", source: "悲陳陶", type: "主旨", question: "《悲陳陶》最能引發讀者哪種感受？", options: ["對戰死者的哀悼與對戰事的沉痛反思", "對英雄的熱烈崇拜", "對自然的悠閒欣賞", "對城市繁華的讚歎"], answer: 0, explanation: "作品重在哀悼義軍與反思戰爭帶來的巨大死亡。", diff: 4 },

      { id: "jtsem2-201", source: "賣炭翁", type: "文言字詞", question: "《賣炭翁》中「南山中」交代了甚麼？", options: ["賣炭地點", "賣炭價格", "賣炭季節", "賣炭對象"], answer: 0, explanation: "「南山中」首先交代賣炭翁工作與生活場域。", diff: 1 },
      { id: "jtsem2-202", source: "賣炭翁", type: "內容理解", question: "「牛困人飢日已高，市南門外泥中歇」最能表現甚麼？", options: ["運炭路途艱苦", "長安市集繁華", "老翁心情輕鬆", "宮使工作辛勞"], answer: 0, explanation: "牛困、人飢、泥中歇，把賣炭之苦寫得非常具體。", diff: 2 },
      { id: "jtsem2-203", source: "賣炭翁", type: "內容理解", question: "賣炭翁最擔心的是甚麼？", options: ["炭賣不出好價錢", "自己太冷受不了", "回家路途太遠", "山中沒有柴伐"], answer: 0, explanation: "詩中明寫「心憂炭賤」。", diff: 2 },
      { id: "jtsem2-204", source: "賣炭翁", type: "思想感情", question: "「願天寒」一句之所以令人心酸，最主要因為甚麼？", options: ["它違反常情，凸顯生計壓力", "老翁天生喜歡冷天", "冬天更適合燒炭", "宮使喜歡在冷天買炭"], answer: 0, explanation: "身上衣正單卻盼天寒，正是貧苦生活造成的反常心理。", diff: 4 },
      { id: "jtsem2-205", source: "賣炭翁", type: "寫作手法", question: "白居易在《賣炭翁》中最有力的地方是甚麼？", options: ["不多議論而讓事實本身說話", "大量使用典故諷刺", "以神怪情節取勝", "以華麗駢句渲染"], answer: 0, explanation: "白描敘事使讀者直接感受宮市的無理與殘酷。", diff: 4 },
      { id: "jtsem2-206", source: "賣炭翁", type: "文言字詞", question: "「驅將」中的「將」在此處最接近哪一項？", options: ["助詞，帶有把、將的意思", "將軍", "率領", "將要"], answer: 0, explanation: "此處是文言常見用法，可理解為「把車趕走」。", diff: 4 },
      { id: "jtsem2-207", source: "賣炭翁", type: "深層理解", question: "《賣炭翁》最值得警惕的，不只是個別官差無良，而是甚麼？", options: ["權力可藉制度之名傷害弱者", "百姓不懂法律", "冬天太冷不適合勞動", "農村經濟難以發展"], answer: 0, explanation: "「口稱敕」正說明權勢與制度名義結合時的可怕。", diff: 5 },
      { id: "jtsem2-208", source: "賣炭翁", type: "主旨理解", question: "《賣炭翁》除了同情老翁，也在提醒讀者甚麼？", options: ["若制度不公，勤勞也可能無法保障生活", "只要勤勞就必致富", "老年人不應工作", "商業交易都不公平"], answer: 0, explanation: "作品指出問題不只在勞苦，而在勞苦者遭制度剝削。", diff: 5 },
      { id: "jtsem2-209", source: "賣炭翁", type: "內容理解", question: "《賣炭翁》中最能代表宮市荒謬的一個細節是甚麼？", options: ["半疋紅紗一丈綾換走千餘斤炭", "賣炭翁伐薪燒炭", "日已高仍未入市", "牛困人飢在泥中休息"], answer: 0, explanation: "極不相稱的交換，正是宮市剝削最直觀的證據。", diff: 3 },
      { id: "jtsem2-210", source: "賣炭翁", type: "賞析", question: "《賣炭翁》讀來沉痛，最大原因之一是甚麼？", options: ["它把生計之苦與制度之惡寫在一起", "它句子特別長", "它完全沒有情節", "它只描寫雪景"], answer: 0, explanation: "作品不只寫勞苦，更寫勞苦者被強權奪取成果。", diff: 5 },

      { id: "jtsem2-211", source: "兵車行", type: "內容理解", question: "《兵車行》中最先被直接看見的是甚麼？", options: ["行軍與送別的場面", "戰後白骨遍野", "農村收成景象", "邊庭宮殿規模"], answer: 0, explanation: "詩篇從行軍出發與家人送別開始鋪陳。", diff: 2 },
      { id: "jtsem2-212", source: "兵車行", type: "內容理解", question: "下列哪一句最能直接指出戰爭造成農田失修？", options: ["千村萬落生荊杞", "爺娘妻子走相送", "武皇開邊意未已", "新鬼煩冤舊鬼哭"], answer: 0, explanation: "荊杞叢生說明農村荒廢，無人耕作。", diff: 2 },
      { id: "jtsem2-213", source: "兵車行", type: "深層理解", question: "《兵車行》寫哭聲、荒村、租稅與白骨，最終形成甚麼整體效果？", options: ["把戰亂寫成全方位社會災難", "只寫出征前的不捨", "只寫自然景色陰沉", "只寫統治者的野心"], answer: 0, explanation: "詩作由局部情景推至全面社會災難，層次極深。", diff: 5 },
      { id: "jtsem2-214", source: "兵車行", type: "寫作手法", question: "《兵車行》中的問答安排，使作品增加了甚麼效果？", options: ["真實感與層層揭露感", "神秘感與離奇感", "輕鬆感與幽默感", "冷漠感與疏離感"], answer: 0, explanation: "問答使苦況不是作者空講，而像由當事人親口道出。", diff: 4 },
      { id: "jtsem2-215", source: "兵車行", type: "內容理解", question: "「生男埋沒隨百草」中最沉痛的地方在於甚麼？", options: ["連屍骨也難有歸宿", "男子比女子命短", "男孩一出生便被遺棄", "百草會掩埋村莊"], answer: 0, explanation: "這句含有戰死無收、埋沒荒野的深沉哀傷。", diff: 4 },
      { id: "jtsem2-216", source: "兵車行", type: "賞析", question: "《兵車行》之所以常被視為「詩史」精神的代表，最主要因為甚麼？", options: ["它用詩記錄時代苦難", "它詳細記錄年份地點", "它像史書一樣無感情", "它只重戰事勝負"], answer: 0, explanation: "杜甫以詩折射時代災難與人民遭遇，故有詩史之稱。", diff: 5 },
      { id: "jtsem2-217", source: "兵車行", type: "人物理解", question: "《兵車行》中的百姓最明顯的特徵是甚麼？", options: ["被動承受戰爭與徵役", "主動爭功請戰", "藉戰爭牟取利益", "完全不受影響"], answer: 0, explanation: "詩中百姓無法主宰命運，只能承受戰亂與苛政。", diff: 3 },
      { id: "jtsem2-218", source: "兵車行", type: "語句理解", question: "「天陰雨濕聲啾啾」一句為何收束得特別沉重？", options: ["把自然環境與鬼哭之聲融合", "因為天氣終於轉好", "因為士兵將要凱旋", "因為百姓回復平靜"], answer: 0, explanation: "陰雨濕冷與啾啾鬼哭相映，更顯戰場淒厲。", diff: 4 },
      { id: "jtsem2-219", source: "兵車行", type: "主旨理解", question: "若要概括《兵車行》最關鍵的批判精神，下列哪一項最準確？", options: ["人民不應成為國家擴張的代價", "將軍不應遠征邊塞", "百姓應勇敢從軍", "地方官應加強徵稅"], answer: 0, explanation: "全詩正是控訴人民成為窮兵黷武的犧牲品。", diff: 5 },
      { id: "jtsem2-220", source: "兵車行", type: "總結理解", question: "《兵車行》最適合作為哪一類文本的學習代表？", options: ["關懷人民的社會批判詩", "純景物詩", "宮廷應制詩", "閒情逸致小品"], answer: 0, explanation: "其核心價值正在於社會批判與人民關懷。", diff: 4 },

      { id: "jtsem2-221", source: "靜虛村記", type: "內容理解", question: "《靜虛村記》中，作者為何反覆寫村中日常瑣事？", options: ["要呈現完整而真切的村居生活", "因為無其他可寫", "想諷刺農村無聊", "只為拖長篇幅"], answer: 0, explanation: "瑣事累積起來，正是靜虛村生命感的來源。", diff: 4 },
      { id: "jtsem2-222", source: "靜虛村記", type: "思想感情", question: "《靜虛村記》最動人的地方之一，在於作者對村子的感情如何變化？", options: ["由初見新鮮到深度融入", "由喜愛轉為厭惡", "由冷漠轉為批評", "由陌生轉為恐懼"], answer: 0, explanation: "作者最初只是借住，後來已與村子情感相連。", diff: 4 },
      { id: "jtsem2-223", source: "靜虛村記", type: "寫作手法", question: "作者把井水、槐花、蝴蝶、蛐蛐等細節連綴起來，最有何效果？", options: ["構成一幅有聲有色的村居圖", "使文章支離破碎", "表現作者知識駁雜", "加重諷刺意味"], answer: 0, explanation: "這些細節共同讓讀者感到村落鮮活可感。", diff: 4 },
      { id: "jtsem2-224", source: "靜虛村記", type: "人物理解", question: "作者在村中輔導作文、記錄村事，最終成了甚麼樣的人？", options: ["村中精神生活的一部分", "村中局外旁觀者", "村中權力中心", "村中最受排斥的人"], answer: 0, explanation: "他不只是居住者，也參與了村子的文化與教育生活。", diff: 5 },
      { id: "jtsem2-225", source: "靜虛村記", type: "主旨理解", question: "《靜虛村記》若用一句話概括，最恰當的是哪一項？", options: ["在城市邊緣重新發現自然與人情的可貴", "記錄作者仕途失敗後的抱怨", "諷刺農村落後閉塞", "說明城市文明的優越"], answer: 0, explanation: "全文核心在重新發現拙樸生活的美與價值。", diff: 5 },

      { id: "jtsem2-226", source: "論四端", type: "內容理解", question: "孟子之所以從「心」說起，而不從制度說起，最主要是因為甚麼？", options: ["他認為制度應根源於人心", "他反對一切制度", "他只關心個人修身", "他不重視社會秩序"], answer: 0, explanation: "孟子相信政治應立基於人的道德本性。", diff: 5 },
      { id: "jtsem2-227", source: "論四端", type: "內容理解", question: "「先王有不忍人之心，斯有不忍人之政」一句最關鍵的意思是甚麼？", options: ["仁政根源於仁心", "先王都反對戰爭", "政治只需君主獨斷", "治國不必依靠人民"], answer: 0, explanation: "這句把內在德性與外在政治直接連結。", diff: 4 },
      { id: "jtsem2-228", source: "論四端", type: "價值理解", question: "《論四端》對今天最重要的提醒之一是甚麼？", options: ["制度改革不能離開道德基礎", "人只要善良就不需法律", "教育無法改變人", "情緒比理性更重要"], answer: 0, explanation: "孟子的思想提醒我們，道德與制度應相互支撐。", diff: 5 },
      { id: "jtsem2-229", source: "論四端", type: "主旨理解", question: "孟子強調四端人人皆有，最能對治哪種錯誤看法？", options: ["只有少數人天生值得成德", "人不需教育也會自動完善", "政治與人性完全無關", "善心只能用在家庭"], answer: 0, explanation: "孟子肯定人人皆有向善的可能與尊嚴。", diff: 4 },
      { id: "jtsem2-230", source: "論四端", type: "賞析", question: "《論四端》既具哲理，又具說服力，關鍵在於甚麼？", options: ["從普遍經驗出發，再推導出道德理論", "全靠權威壓人", "只用抽象概念堆砌", "只靠情緒煽動"], answer: 0, explanation: "孟子的高明之處，在於由人人可體會的經驗推及理論。", diff: 5 },

      { id: "jtsem2-231", source: "大同與小康", type: "內容理解", question: "《大同與小康》若從「人」與「制度」關係來看，大同偏重甚麼？", options: ["人心與公德", "城郭與防衛", "世襲與權位", "功名與競爭"], answer: 0, explanation: "大同首先強調公心、信任與和睦。", diff: 4 },
      { id: "jtsem2-232", source: "大同與小康", type: "內容理解", question: "《大同與小康》中的小康部分，最能顯示現實政治哪一面？", options: ["必須用禮義制度維持秩序", "不需任何法度即可太平", "理想必然完全實現", "人人完全無私"], answer: 0, explanation: "小康社會已不如大同純善，因此需依靠制度與禮義。", diff: 4 },
      { id: "jtsem2-233", source: "大同與小康", type: "價值理解", question: "《大同與小康》對讀者最大的啟發之一是甚麼？", options: ["應同時思考理想目標與現實安排", "現實一定無法改變", "理想社會毫無意義", "制度必然比人心重要"], answer: 0, explanation: "文章讓人明白，理想與現實並非絕對對立，而需同時思考。", diff: 5 },
      { id: "jtsem2-234", source: "大同與小康", type: "主旨理解", question: "若以儒家角度看，《大同與小康》的核心不在描述制度形式，而更在甚麼？", options: ["維繫和諧社會的道德與秩序原則", "國家版圖大小", "軍隊數目多少", "城市建築規模"], answer: 0, explanation: "大同與小康都圍繞社會秩序與人倫價值展開。", diff: 5 },
      { id: "jtsem2-235", source: "大同與小康", type: "賞析", question: "《大同與小康》之所以歷久常新，最主要因為它提出了甚麼問題？", options: ["理想社會應如何成為可能", "哪位君王最能征戰", "哪個朝代最富庶", "哪種建築最安全"], answer: 0, explanation: "這篇文章真正重要之處，在於對理想社會與現實秩序的持續提問。", diff: 5 },

      { id: "jtsem2-236", source: "悲陳陶", type: "文言字詞", question: "《悲陳陶》中「血作陳陶澤」的「作」可理解為甚麼？", options: ["化作", "製作", "開始", "發作"], answer: 0, explanation: "此處「作」有化成、變成之意。", diff: 3 },
      { id: "jtsem2-237", source: "悲陳陶", type: "內容理解", question: "《悲陳陶》最能令人感到沉痛的原因之一是甚麼？", options: ["死者是大量普通人家子弟", "將軍地位太高", "戰場太過遙遠", "景色太過清幽"], answer: 0, explanation: "「良家子」使死亡更具普遍性與民間悲劇性。", diff: 4 },
      { id: "jtsem2-238", source: "悲陳陶", type: "主旨理解", question: "《悲陳陶》最適合作為哪一類作品代表？", options: ["戰爭哀悼詩", "山水閒適詩", "送別曲", "性善論說文"], answer: 0, explanation: "全詩集中於哀悼戰敗後的巨大死傷。", diff: 3 },
      { id: "jtsem2-239", source: "悲陳陶", type: "賞析", question: "《悲陳陶》的震撼力主要來自哪一項？", options: ["極簡而慘烈的戰後畫面", "長篇敘事交代完整經過", "複雜人物對話", "細膩兒女私情"], answer: 0, explanation: "詩篇並不長，卻用凝縮筆法寫出極重的悲感。", diff: 4 },
      { id: "jtsem2-240", source: "悲陳陶", type: "深層理解", question: "《悲陳陶》與《兵車行》都讓人看到甚麼？", options: ["戰爭背後被犧牲的是人民", "戰爭能快速致富", "戰場最能成就個人理想", "將軍比百姓更重要"], answer: 0, explanation: "兩篇共同聚焦戰爭對普通生命的吞噬。", diff: 5 },

      { id: "jtsem2-241", source: "賣炭翁", type: "文言字詞", question: "《賣炭翁》中「一丈綾」中的「綾」是甚麼？", options: ["絲織品", "棉布", "皮革", "麻繩"], answer: 0, explanation: "「綾」是較為華貴的絲織品。", diff: 2 },
      { id: "jtsem2-242", source: "賣炭翁", type: "內容理解", question: "「心憂炭賤願天寒」被視為名句，最主要因為它寫出了甚麼？", options: ["窮苦者受生計逼迫的扭曲心情", "作者對冬天的喜愛", "商人投機的快樂", "宮市制度的公平"], answer: 0, explanation: "這句高度濃縮了貧苦生活的荒謬與悲哀。", diff: 4 },
      { id: "jtsem2-243", source: "賣炭翁", type: "內容理解", question: "《賣炭翁》中，老翁的所有辛勞最終換來甚麼？", options: ["極不相稱的微薄布匹", "滿車白銀", "官府表揚", "溫飽生活"], answer: 0, explanation: "這樣的結局強化了作品對宮市的控訴。", diff: 3 },
      { id: "jtsem2-244", source: "賣炭翁", type: "主旨理解", question: "《賣炭翁》最深層的批判對象是誰？", options: ["以皇命為名行掠奪之實的權力體系", "個人懶惰的窮人", "普通商販", "冬日嚴寒"], answer: 0, explanation: "作品真正批判的是制度與權力，而不只是個別人物。", diff: 5 },
      { id: "jtsem2-245", source: "賣炭翁", type: "賞析", question: "白居易不大聲咒罵宮使，而只寫其行為，這樣做最有何效果？", options: ["讓讀者自行感受其可惡", "削弱批判力度", "使作品變得平淡", "使宮使顯得可憐"], answer: 0, explanation: "不直斥反而更有力量，因為事實本身已足夠令人憤怒。", diff: 5 },

      { id: "jtsem2-246", source: "元曲四首對讀", type: "對讀比較", question: "《沉醉東風・送別》與《端正好・長亭送別》都屬送別作品，但哪一首更重景？", options: ["《端正好・長亭送別》", "《沉醉東風・送別》", "兩者都不重景", "兩者完全相同"], answer: 0, explanation: "《端正好》以秋景鋪陳最為典型。", diff: 3 },
      { id: "jtsem2-247", source: "元曲四首對讀", type: "對讀比較", question: "《四塊玉・閒適》兩首與《天淨沙・魯卿庵中》相比，前者較多甚麼特色？", options: ["生活化與口語感", "戰爭感與史事感", "議論性與哲理性", "宮廷氣與典重感"], answer: 0, explanation: "《四塊玉》語氣更生活化、更貼近日常。", diff: 4 },
      { id: "jtsem2-248", source: "元曲四首對讀", type: "對讀比較", question: "《天淨沙・魯卿庵中》與《四塊玉・閒適》其二都可引向哪一種人生態度？", options: ["淡遠自適", "功名競逐", "報國從軍", "制度批判"], answer: 0, explanation: "兩者都帶出一種看淡世俗、偏向清靜閒適的心境。", diff: 4 },
      { id: "jtsem2-249", source: "元曲四首對讀", type: "主旨理解", question: "若為元曲四首設一個總題，下列哪一項最恰當？", options: ["離情與閒情中的元曲風貌", "戰亂與民苦", "仁政與禮治", "宮市與邊塞"], answer: 0, explanation: "元曲四首主要可分為送別離情與閒適情趣兩類。", diff: 4 },
      { id: "jtsem2-250", source: "元曲四首對讀", type: "深層理解", question: "元曲四首共同告訴讀者，元曲不只能寫甚麼，也能寫甚麼？", options: ["不只能寫熱鬧口語，也能寫深細情味", "不只能寫戰爭，也只能寫戰爭", "不只能說理，也只能說理", "不只能記史，也只能記史"], answer: 0, explanation: "元曲可口語、可清雅、可送別、可閒適，表現面向很豐富。", diff: 5 },

      { id: "jtsem2-251", source: "兵車行", type: "內容理解", question: "《兵車行》中，最能表現人民被迫從軍且難以脫身的是哪一句？", options: ["去時里正與裹頭，歸來頭白還戍邊", "車轔轔，馬蕭蕭", "邊庭流血成海水", "新鬼煩冤舊鬼哭"], answer: 0, explanation: "這句最直接寫出兵役從少年延續到老年。", diff: 3 },
      { id: "jtsem2-252", source: "兵車行", type: "內容理解", question: "《兵車行》中，「未休關西卒」說明甚麼？", options: ["戰事連年不止", "士兵即將回家", "百姓不再徵兵", "邊關已經安定"], answer: 0, explanation: "「未休」表示兵役仍未停止。", diff: 3 },
      { id: "jtsem2-253", source: "兵車行", type: "內容理解", question: "杜甫在《兵車行》中寫到農村荒蕪，主要是為了甚麼？", options: ["說明戰爭影響遠不止戰場", "描寫自然景物奇特", "表現農村懶散", "說明婦女不會耕作"], answer: 0, explanation: "詩人要指出戰亂對整個社會生產與民生的破壞。", diff: 4 },
      { id: "jtsem2-254", source: "兵車行", type: "賞析", question: "《兵車行》的成功，與它善於「以小見大」有關，這裡的「小」最先是甚麼？", options: ["一個送別場面", "一場凱旋典禮", "一個邊地市場", "一處宮廷宴會"], answer: 0, explanation: "全詩由眼前的送別起筆，逐步寫出時代大悲劇。", diff: 4 },
      { id: "jtsem2-255", source: "兵車行", type: "深層理解", question: "若以《兵車行》反思現代社會，最可得到哪種啟示？", options: ["政策若脫離人民處境，後果將極為沉重", "戰爭一定能帶來繁榮", "犧牲總是必要而光榮", "普通人不需關心政治"], answer: 0, explanation: "杜甫的詩正是提醒人們政治與人民生活不能割裂。", diff: 5 },

      { id: "jtsem2-256", source: "靜虛村記", type: "內容理解", question: "《靜虛村記》中，作者何以說自己在村裡「看書作文有了精神、靈性」？", options: ["因自然環境與村居生活滋養身心", "因村裡藏書特別多", "因城市生活完全無書讀", "因村人天天催促他寫作"], answer: 0, explanation: "井水、土院、自然與人情共同構成作者精神煥發的來源。", diff: 4 },
      { id: "jtsem2-257", source: "靜虛村記", type: "內容理解", question: "作者寫「風止月瞑，露珠閃閃，一片蛐蛐鳴叫」，最適合用來概括為甚麼？", options: ["村夜靜美", "城中繁華", "戰後淒涼", "送別哀婉"], answer: 0, explanation: "這是全文最後凝縮的夜景意境。", diff: 3 },
      { id: "jtsem2-258", source: "靜虛村記", type: "賞析", question: "《靜虛村記》寫村人與作者一家之互動，最能讓讀者感受到甚麼？", options: ["生活共同體的溫度", "嚴密的政治制度", "尖銳的社會批判", "激烈的人物衝突"], answer: 0, explanation: "全篇最動人處之一正是這種彼此往來的人情厚度。", diff: 4 },
      { id: "jtsem2-259", source: "靜虛村記", type: "主旨理解", question: "《靜虛村記》與一般單純寫景散文的差別，在於它更著重甚麼？", options: ["人與地方彼此成全的關係", "氣候變化的規律", "建築材料的分析", "地方交通位置的優勢"], answer: 0, explanation: "作者不只是描景，而是寫自己在村中的生命轉變與歸屬。", diff: 5 },
      { id: "jtsem2-260", source: "靜虛村記", type: "深層理解", question: "《靜虛村記》可視為一篇怎樣的文章？", options: ["以村居經驗重整現代人生活感受的散文", "專門批評農村衛生的雜文", "單純記錄植物種類的說明文", "討論制度改革的論說文"], answer: 0, explanation: "作者透過靜虛村重新思考現代城市與自然生活的關係。", diff: 5 },

      { id: "jtsem2-261", source: "論四端", type: "內容理解", question: "《論四端》中，孟子由孺子入井推出何種更普遍的結論？", options: ["人都本具道德善端", "人看到危險都會害怕", "父母與孩子關係最深", "社會需要更多法律"], answer: 0, explanation: "孺子入井只是例子，真正結論是人人本有四端。", diff: 3 },
      { id: "jtsem2-262", source: "論四端", type: "思想理解", question: "孟子說「先王有不忍人之心，斯有不忍人之政」，可見他認為政治首先要靠甚麼？", options: ["道德心", "軍事力", "財富", "技術"], answer: 0, explanation: "孟子認為仁政根本在於統治者是否具有不忍人之心。", diff: 4 },
      { id: "jtsem2-263", source: "論四端", type: "價值理解", question: "若把《論四端》應用在教育上，最合理的理解是甚麼？", options: ["教育應喚醒並引導人的善性", "教育只需灌輸規則", "教育應完全依靠懲罰", "教育不應涉及道德"], answer: 0, explanation: "依孟子之見，教育的重要工作之一正是引導善端發展。", diff: 5 },
      { id: "jtsem2-264", source: "論四端", type: "主旨理解", question: "《論四端》能成為經典，與其哪一項特質最相關？", options: ["把日常經驗提升為道德與政治思考", "完全避免談現實問題", "只列舉概念不論證", "專重文辭華美"], answer: 0, explanation: "孟子由日常感受推及德性與仁政，因此歷久不衰。", diff: 5 },
      { id: "jtsem2-265", source: "論四端", type: "深層理解", question: "《論四端》最終想反駁的，不只是「人無善端」，還包括哪種看法？", options: ["道德與政治彼此無關", "人需要家庭", "人需要朋友", "人會怕危險"], answer: 0, explanation: "孟子最終把善端推向仁政，因此也反駁道德與政治割裂的想法。", diff: 5 },

      { id: "jtsem2-266", source: "大同與小康", type: "內容理解", question: "《大同與小康》中，大同社會最可貴的是甚麼？", options: ["人人能超越私利而顧及眾人", "每家財物最多", "君主權力最強", "軍事制度最完備"], answer: 0, explanation: "大同的核心在公而不私、和睦共享。", diff: 3 },
      { id: "jtsem2-267", source: "大同與小康", type: "內容理解", question: "《大同與小康》中，小康社會最現實的一面是甚麼？", options: ["承認人有私心，因此須以制度規範", "認為人人都能完全無私", "拒絕一切家族關係", "不需要任何秩序"], answer: 0, explanation: "小康之治正是承認現實人性與社會情況，故需禮義制度。", diff: 4 },
      { id: "jtsem2-268", source: "大同與小康", type: "思想理解", question: "若以現代語概括「天下為公」，最接近哪一項？", options: ["以公共利益為重", "人人財產相同", "國家沒有政府", "只聽君主命令"], answer: 0, explanation: "「天下為公」強調公共性與非私有化的政治倫理。", diff: 4 },
      { id: "jtsem2-269", source: "大同與小康", type: "主旨理解", question: "《大同與小康》不是純幻想的原因之一是甚麼？", options: ["它同時討論理想與次善秩序", "它只寫歷史故事", "它拒絕所有制度", "它否定禮義價值"], answer: 0, explanation: "文章最深的地方在於兼顧理想與現實。", diff: 5 },
      { id: "jtsem2-270", source: "大同與小康", type: "深層理解", question: "《大同與小康》對今日社會討論最有啟發的一點是甚麼？", options: ["社會設計需兼顧理想價值與可行秩序", "理想一定會阻礙現實", "只靠現實利益即可維持穩定", "制度與道德可以完全分離"], answer: 0, explanation: "孔子並未只談空理想，而是也正視現實社會治理問題。", diff: 5 },

      { id: "jtsem2-271", source: "兵車行／悲陳陶對讀", type: "對讀比較", question: "《兵車行》與《悲陳陶》最共同的主題是甚麼？", options: ["戰爭對人民的傷害", "村居生活之美", "送別時的柔情", "理想社會秩序"], answer: 0, explanation: "兩篇都聚焦戰爭造成的大量人民苦難。", diff: 4 },
      { id: "jtsem2-272", source: "賣炭翁／兵車行對讀", type: "對讀比較", question: "《賣炭翁》與《兵車行》共同批判的是甚麼？", options: ["脫離民本的權力運作", "村落生活閉塞", "士兵怯戰懶惰", "文人過於感傷"], answer: 0, explanation: "一篇寫宮市，一篇寫戰禍與徵役，都批判失去民本的政治。", diff: 5 },
      { id: "jtsem2-273", source: "論四端／賣炭翁對讀", type: "對讀比較", question: "《論四端》若用來反觀《賣炭翁》，最能看出甚麼？", options: ["掌權者缺乏不忍人之心", "賣炭翁缺乏義心", "人民不懂禮讓", "制度比人心更重要"], answer: 0, explanation: "如果政治有仁心，就不會縱容宮市剝削百姓。", diff: 5 },
      { id: "jtsem2-274", source: "大同與小康／靜虛村記對讀", type: "對讀比較", question: "《靜虛村記》與《大同與小康》相互參照時，最能連結的觀念是甚麼？", options: ["和睦與互助的生活秩序", "戰爭與徵兵", "君王與將軍", "城市與市場"], answer: 0, explanation: "靜虛村中的人情厚誠，可視為理想社會精神的具體日常呈現。", diff: 5 },
      { id: "jtsem2-275", source: "論四端／大同與小康對讀", type: "對讀比較", question: "《論四端》與《大同與小康》若合起來看，最能說明甚麼？", options: ["理想社會需建立於人的善端與德性", "理想社會只靠制度即可", "道德只是私人事情", "社會秩序與人心無關"], answer: 0, explanation: "四端提供人心基礎，大同則呈現社會層次的理想。", diff: 5 },

      { id: "jtsem2-276", source: "元曲四首", type: "元曲格律", question: "元曲中的「曲牌名」主要規定甚麼？", options: ["格律與調式框架", "作品唯一主題", "作者身份", "歷史背景"], answer: 0, explanation: "曲牌主要關乎形式格律，不限定唯一內容。", diff: 3 },
      { id: "jtsem2-277", source: "元曲四首", type: "元曲格律", question: "學習元曲時，知道曲牌名有何幫助？", options: ["理解作品形式與體裁歸屬", "直接知道所有內容", "立刻判斷作者生平", "推知戰爭背景"], answer: 0, explanation: "辨識曲牌名是掌握元曲形式的重要一步。", diff: 3 },
      { id: "jtsem2-278", source: "元曲四首", type: "內容理解", question: "元曲四首中的「送別」與「閒適」兩類題材，分別偏重甚麼？", options: ["前者重離情，後者重自得", "前者重說理，後者重記史", "前者重戰事，後者重官場", "前者重制度，後者重人性"], answer: 0, explanation: "這是本組元曲最清楚的分類方式。", diff: 3 },
      { id: "jtsem2-279", source: "元曲四首", type: "賞析", question: "元曲之所以易於傳情，與它哪一項特性很有關係？", options: ["節奏鮮明、語言靈活", "篇幅冗長、論證嚴密", "典故艱深、語意晦澀", "格式死板、不可變通"], answer: 0, explanation: "元曲富音樂性，語言也靈活，因此特別容易傳情。", diff: 4 },
      { id: "jtsem2-280", source: "元曲四首", type: "深層理解", question: "若把元曲四首放在一起學習，最重要的能力之一是甚麼？", options: ["辨別不同情境下的景與情如何結合", "只背誦曲牌名即可", "只記住作者朝代", "只分析押韻位置"], answer: 0, explanation: "這組作品都很適合訓練情景關係與文體感受力。", diff: 5 },

      { id: "jtsem2-281", source: "沉醉東風・送別", type: "內容理解", question: "《沉醉東風・送別》中最直接打動人的地方是甚麼？", options: ["離情表達坦率真切", "典故繁多華麗", "場面壯闊雄渾", "議論深入周密"], answer: 0, explanation: "此曲的力量正在於情感表達直接而真摯。", diff: 3 },
      { id: "jtsem2-282", source: "沉醉東風・送別", type: "元曲格律", question: "《沉醉東風・送別》在文體上最應注意哪一項？", options: ["它是曲，不是詩", "它是古文，不是曲", "它是駢文，不是曲", "它是賦，不是曲"], answer: 0, explanation: "學習時需先辨清其元曲小令身份。", diff: 2 },
      { id: "jtsem2-283", source: "沉醉東風・送別", type: "賞析", question: "此曲中的「餞行杯」與「別離淚」形成甚麼效果？", options: ["外在場面與內在情緒並寫", "以物喻志", "以景寫戰", "以議論收束"], answer: 0, explanation: "杯與淚一實一虛，合起來正好表現送別場面與情緒。", diff: 4 },
      { id: "jtsem2-284", source: "沉醉東風・送別", type: "主旨理解", question: "《沉醉東風・送別》若用一句話概括，最恰當的是哪一項？", options: ["在直白語言中寫出難分難捨的送別情", "在秋景中寫戰亂之苦", "在鄉村中寫自然之美", "在說理中談人性善端"], answer: 0, explanation: "本曲最重要的特點正是口語直率地表達送別。", diff: 4 },
      { id: "jtsem2-285", source: "沉醉東風・送別", type: "深層理解", question: "《沉醉東風・送別》之所以適合初學元曲者閱讀，原因之一是甚麼？", options: ["情感與語言都較直接", "格律最複雜", "典故最多", "全篇最抽象"], answer: 0, explanation: "此曲在語言與情感上都較容易把握。", diff: 4 },

      { id: "jtsem2-286", source: "四塊玉・閒適（其一）", type: "內容理解", question: "《四塊玉・閒適》其一最重視哪一種快樂？", options: ["與人共享的日常之樂", "征戰立功之樂", "離別成長之樂", "辯論得勝之樂"], answer: 0, explanation: "作品從飲食與相聚表現平凡生活的樂趣。", diff: 3 },
      { id: "jtsem2-287", source: "四塊玉・閒適（其一）", type: "賞析", question: "其一把食物與相聚寫得生動，主要是為了甚麼？", options: ["使閒適之樂具體可感", "展現作者廚藝高明", "諷刺鄉村粗俗", "描寫窮困生活"], answer: 0, explanation: "作品不是寫美食本身，而是寫生活情趣。", diff: 4 },
      { id: "jtsem2-288", source: "四塊玉・閒適（其一）", type: "主旨理解", question: "《四塊玉・閒適》其一可視為對哪種價值的肯定？", options: ["平淡生活也能有可貴情味", "只有豪華生活才算快樂", "功名是人生唯一目標", "離群索居才最自由"], answer: 0, explanation: "曲中處處體現對平凡閒樂的欣賞。", diff: 4 },
      { id: "jtsem2-289", source: "四塊玉・閒適（其一）", type: "元曲格律", question: "其一的語言帶有較強口語感，最能說明元曲哪一特色？", options: ["俗中見真趣", "句法最嚴整", "格律最死板", "內容最抽象"], answer: 0, explanation: "元曲往往以近口語的語言表現真切情趣。", diff: 4 },
      { id: "jtsem2-290", source: "四塊玉・閒適（其一）", type: "深層理解", question: "《四塊玉・閒適》其一中的閒適，其實並不空泛，因為它建立在甚麼之上？", options: ["具體的人情互動與生活實感", "對權力的掌控", "對制度的批判", "對歷史的考證"], answer: 0, explanation: "作品的閒適來自共享與日常，而非抽象概念。", diff: 5 },

      { id: "jtsem2-291", source: "四塊玉・閒適（其二）", type: "內容理解", question: "《四塊玉・閒適》其二中，看透世態後的作者選擇甚麼？", options: ["不再與人爭高下", "更加積極求仕", "投入戰場立功", "遠走他鄉經商"], answer: 0, explanation: "「爭甚麼」最能表現這種選擇。", diff: 3 },
      { id: "jtsem2-292", source: "四塊玉・閒適（其二）", type: "賞析", question: "其二的深味主要來自甚麼？", options: ["用平易語言表達人生體會", "奇詭神怪的想像", "長篇鋪陳家世", "歷史典故連篇"], answer: 0, explanation: "此曲語言平淺，但意味深長。", diff: 4 },
      { id: "jtsem2-293", source: "四塊玉・閒適（其二）", type: "主旨理解", question: "《四塊玉・閒適》其二最能提醒讀者甚麼？", options: ["經歷世態後仍可保持從容", "人生必須競爭到底", "只有贏過別人才算成功", "看透世事等於消極絕望"], answer: 0, explanation: "作品重點是看透後的淡泊，不是厭世。", diff: 4 },
      { id: "jtsem2-294", source: "四塊玉・閒適（其二）", type: "元曲格律", question: "其二雖談人生感慨，仍保有元曲甚麼明顯特徵？", options: ["語言靈活自然", "論證嚴密如策論", "句法整齊如律詩", "完全排斥口語"], answer: 0, explanation: "即使談人生感慨，元曲仍保持自然靈活的語言風格。", diff: 4 },
      { id: "jtsem2-295", source: "四塊玉・閒適（其二）", type: "深層理解", question: "《四塊玉・閒適》其二並非要人消極，而是要人學會甚麼？", options: ["不被俗世評價綁住", "永遠躲避人群", "拒絕所有責任", "放棄任何理想"], answer: 0, explanation: "作者重點在於從容面對世俗，不盲目爭勝。", diff: 5 },

      { id: "jtsem2-296", source: "天淨沙・魯卿庵中", type: "內容理解", question: "《天淨沙・魯卿庵中》中景物排列最突出的作用是甚麼？", options: ["層層營造空間與意境", "交代軍事部署", "描述市場繁榮", "鋪陳宴會熱鬧"], answer: 0, explanation: "景物由近及遠、由靜到微動，形成豐富層次。", diff: 3 },
      { id: "jtsem2-297", source: "天淨沙・魯卿庵中", type: "賞析", question: "作品中的「探梅人」之妙，最主要在於甚麼？", options: ["在幽靜中添入一絲人間雅趣", "帶來激烈衝突", "象徵戰事將起", "表現人物孤獨"], answer: 0, explanation: "這一筆使全篇不止靜景，也有文人氣息。", diff: 4 },
      { id: "jtsem2-298", source: "天淨沙・魯卿庵中", type: "主旨理解", question: "《天淨沙・魯卿庵中》最適合以下哪一項概括？", options: ["以精簡景語寫閒雅幽境", "以長敘事寫家國大事", "以問答論證說理", "以人物衝突推情節"], answer: 0, explanation: "其精華正在於極簡的造境能力。", diff: 4 },
      { id: "jtsem2-299", source: "天淨沙・魯卿庵中", type: "元曲格律", question: "《天淨沙・魯卿庵中》最能作為哪種學習範例？", options: ["短章造境", "長篇敘事", "政論駁辯", "宮體豔情"], answer: 0, explanation: "這首小令最適合用來學「短而有境」。", diff: 4 },
      { id: "jtsem2-300", source: "天淨沙・魯卿庵中", type: "深層理解", question: "若說《天淨沙・魯卿庵中》是「景中有心」，其中的「心」最接近哪一項？", options: ["閒靜淡遠", "悲憤激烈", "慷慨報國", "焦躁功利"], answer: 0, explanation: "景之清幽正映現心之靜遠。", diff: 5 },

      { id: "jtsem2-301", source: "端正好・長亭送別", type: "內容理解", question: "《端正好・長亭送別》中，最先給人感受的是甚麼？", options: ["濃濃秋意", "戰場肅殺", "村居閒適", "宮廷奢華"], answer: 0, explanation: "碧雲、黃花、西風、北雁，一開始就把秋意鋪開。", diff: 2 },
      { id: "jtsem2-302", source: "端正好・長亭送別", type: "賞析", question: "「曉來誰染霜林醉」一句為何特別傳神？", options: ["把自然景象寫得像有感情一樣", "說明霜林真的喝醉了", "描寫樹木顏色不正常", "只是單純發問"], answer: 0, explanation: "這句把秋林染紅與離人情感巧妙結合。", diff: 4 },
      { id: "jtsem2-303", source: "端正好・長亭送別", type: "內容理解", question: "長亭在中國文學中常與哪一種情境相連？", options: ["送別", "祭祀", "戰鬥", "宴飲"], answer: 0, explanation: "長亭常是古人送別停駐之地。", diff: 2 },
      { id: "jtsem2-304", source: "端正好・長亭送別", type: "主旨理解", question: "《端正好・長亭送別》最主要是在寫哪一種關係？", options: ["景與情互相映發", "義與利互相衝突", "人與制度互相牽制", "戰與和互相消長"], answer: 0, explanation: "這首曲最典型的就是情景交融。", diff: 4 },
      { id: "jtsem2-305", source: "端正好・長亭送別", type: "深層理解", question: "《端正好・長亭送別》比一般直接說「我很傷心」更動人，最主要因為甚麼？", options: ["它讓離愁滲入景物之中", "它完全不寫感情", "它只用典故表達", "它全靠故事懸念"], answer: 0, explanation: "景物承載情感，比直接表白更有餘味。", diff: 5 },

      { id: "jtsem2-306", source: "元曲四首對讀", type: "對讀比較", question: "《沉醉東風・送別》與《端正好・長亭送別》若合看，最可作為哪一類學習重點？", options: ["送別元曲的不同表達方式", "反戰詩的不同立場", "村居散文的不同筆法", "說理文的不同論證"], answer: 0, explanation: "兩首送別曲一偏直抒，一偏景抒。", diff: 4 },
      { id: "jtsem2-307", source: "元曲四首對讀", type: "對讀比較", question: "《四塊玉》兩首與《天淨沙・魯卿庵中》若合看，最能作為哪一類學習重點？", options: ["閒適元曲的不同層次", "戰爭詩的不同面向", "宮市題材的不同批判", "儒家思想的不同流派"], answer: 0, explanation: "它們都屬閒適情趣，但一重生活、一重人生、一重意境。", diff: 4 },
      { id: "jtsem2-308", source: "元曲四首對讀", type: "元曲格律", question: "元曲四首合看時，最適合提醒學生注意哪一點？", options: ["曲牌名與題目不可混淆", "所有元曲都不押韻", "所有元曲都是白話文", "所有元曲都寫同一主題"], answer: 0, explanation: "學習元曲，先分清曲牌與題目是基本功。", diff: 4 },
      { id: "jtsem2-309", source: "元曲四首對讀", type: "內容理解", question: "元曲四首中，哪一首最明顯透過秋景寫離愁？", options: ["《端正好・長亭送別》", "《四塊玉・閒適》其一", "《四塊玉・閒適》其二", "《天淨沙・魯卿庵中》"], answer: 0, explanation: "《端正好》的碧雲、黃花、西風、北雁皆為典型秋景離愁。", diff: 3 },
      { id: "jtsem2-310", source: "元曲四首對讀", type: "深層理解", question: "從元曲四首可見，元曲最擅長的是甚麼？", options: ["在短篇幅中兼顧節奏、畫面與情感", "詳細記錄歷史戰爭", "抽象論證哲理", "大規模敘事鋪陳"], answer: 0, explanation: "這正是元曲文體最鮮明的優勢之一。", diff: 5 },

      { id: "jtsem2-311", source: "悲陳陶／賣炭翁對讀", type: "對讀比較", question: "《悲陳陶》與《賣炭翁》若放在一起學，最適合引導學生思考甚麼？", options: ["不同制度與情勢如何壓迫普通人", "哪種景色更美", "哪位作者官位更高", "哪一篇押韻更整齊"], answer: 0, explanation: "一是戰爭，一是宮市，兩種現實都壓迫人民。", diff: 4 },
      { id: "jtsem2-312", source: "悲陳陶／賣炭翁對讀", type: "對讀比較", question: "《悲陳陶》與《賣炭翁》共同不重哪一項？", options: ["個人英雄傳奇", "人民遭遇", "社會批判", "深沉哀感"], answer: 0, explanation: "兩篇都不是英雄史詩，而是人民苦難之詩。", diff: 4 },
      { id: "jtsem2-313", source: "悲陳陶／賣炭翁對讀", type: "文言字詞", question: "若以詞義訓練而言，《悲陳陶》與《賣炭翁》同樣需要學生注意甚麼？", options: ["古詞在語境中的準確理解", "外來語拼寫", "現代口語俗字", "數學符號用法"], answer: 0, explanation: "兩篇都適合訓練從上下文理解古詞。", diff: 3 },
      { id: "jtsem2-314", source: "悲陳陶／賣炭翁對讀", type: "主旨理解", question: "《悲陳陶》與《賣炭翁》最能共同證明哪一點？", options: ["文學能替無聲者發聲", "百姓生活與政治無關", "苦難只能以史書記錄", "詩歌只能抒私人感情"], answer: 0, explanation: "兩篇都為弱者與苦難者留下了深刻的文學見證。", diff: 5 },
      { id: "jtsem2-315", source: "悲陳陶／賣炭翁對讀", type: "深層理解", question: "若把《悲陳陶》與《賣炭翁》放在現代課堂中，最值得討論的價值是甚麼？", options: ["對結構性不公保持敏感", "學習如何經商獲利", "學習如何避免工作", "理解奢華生活魅力"], answer: 0, explanation: "這兩篇都提醒讀者關注制度、權力與人民之間的關係。", diff: 5 },

      { id: "jtsem2-316", source: "兵車行／賣炭翁／悲陳陶", type: "對讀比較", question: "《兵車行》《賣炭翁》《悲陳陶》三篇共同可歸入哪一個主題？", options: ["社會苦難書寫", "閒適散曲", "理想政治論述", "送別抒情"], answer: 0, explanation: "三篇都以不同方式呈現人民受苦。", diff: 4 },
      { id: "jtsem2-317", source: "論四端／大同與小康", type: "對讀比較", question: "《論四端》與《大同與小康》共同可歸入哪個主題？", options: ["儒家人性與社會理想", "元曲格律", "戰亂民生", "閒居生活"], answer: 0, explanation: "前者重人性德性，後者重社會秩序，皆屬儒家思想核心。", diff: 4 },
      { id: "jtsem2-318", source: "靜虛村記／元曲四首", type: "對讀比較", question: "《靜虛村記》與元曲中的閒適作品共同之處較接近哪一項？", options: ["都欣賞平淡生活與清幽情味", "都控訴戰爭災難", "都強調制度設計", "都寫宮市不公"], answer: 0, explanation: "《靜虛村記》與《四塊玉》《天淨沙》都能引向閒適、自然、人情。", diff: 4 },
      { id: "jtsem2-319", source: "四篇課文＋元曲＋唐詩對讀", type: "綜合理解", question: "若把所有這些課文放在一起學習，最可形成哪種整體理解？", options: ["文學能從不同角度觀照人心、社會與生活", "所有作品都只寫景", "所有作品都只說理", "所有作品都只記史"], answer: 0, explanation: "這批課文涵蓋義理、理想社會、民生苦難、送別與閒適等多面向。", diff: 5 },
      { id: "jtsem2-320", source: "四篇課文＋元曲＋唐詩對讀", type: "總結理解", question: "整套課文與元曲、唐詩綜合來看，最核心的學習能力是甚麼？", options: ["理解文本、比較異同、連結思想與情境", "只背作者資料", "只記朝代年代", "只默寫原文"], answer: 0, explanation: "真正重要的是理解內容、比較文本，並連結其背後思想與情境。", diff: 5 }
    ]
  };

  window.BANK_JT_SEM2 = BANK_JT_SEM2;
})();
